### ISSUE TITLE
Missing indicators for SimpleScreenRecorder and Dropbox

### ISSUE THREAD

**Issue by Ads20000** [ubuntu/gnome-shell-extension-appindicator#100]
For SSR, see [here](https://github.com/MaartenBaert/ssr/issues/566#issuecomment-338494888)

With Dropbox, on first boot of Ubuntu 17.10 (after upgrade from 17.04), I got an indicator but it would sometimes load both the non-themed menu and the themed/integrated one when I clicked on it. Now I get no indicator at all. [I don't think the `XDG_CURRENT_DESKTOP` thing is to blame here.](https://github.com/MaartenBaert/ssr/issues/566#issuecomment-326757004)

**Comment by legluondunet** [comment]
no Dropbox icon for me too

**Comment by inverse** [comment]
I get this on first boot, however when locking or upgrading extension I lose this icon. 

ubuntu 17.10 also.

**Comment by jhasse** [comment]
> I don't think the XDG_CURRENT_DESKTOP thing is to blame here.

Have you tried setting it to `Unity`?

> I get this on first boot, however when locking or upgrading extension I lose this icon.

See #75.

**Comment by Ads20000** [comment]
> Have you tried setting it to Unity?

Works for Dropbox thanks (though [as per didrocks' blog](https://didrocks.fr/2017/08/23/ubuntu-gnome-shell-in-artful-day-7/) is it meant to be Unity:Unity7?). Also, how would it be possible to get this working out-of-the-box?

**Comment by jhasse** [comment]
> Also, how would it be possible to get this working out-of-the-box?

Dropbox needs to fix it :/

For SimpleScreenRecorder: Do you know if that also works with `Unity`?

**Comment by Ads20000** [comment]
No the indicator doesn't load at all :(

**Comment by jhasse** [comment]
Okay finally had the time to look at SSR. It's using the Qt tray implementation, which seems to prefer the legacy tray implementation on Xorg. The icon will work, if you start simplescreenrecorder like this:

```
env QT_QPA_PLATFORM=wayland simplescreenrecorder
```

(You'll need to be running Wayland of course)

This needs to be fixed upstream by Qt. The best bug report about it I could find was https://bugreports.qt.io/browse/QTBUG-34364

**Comment by DroWnThePoor** [comment]
@jhasse I'm experiencing this issue on Elementary OS Loki(Ubuntu 16.04),
However, I also have an Arch Labs machine with OpenBox/XFCE using Tint2 as my panel, 
and on that desktop I get an empty space that I can right click and still get the menu for SSR.
Your fix says Wayland is mandatory, so no workaround known with x11?

**Comment by jhasse** [comment]
Yes
