### ISSUE TITLE
Add option to use native context menus

### ISSUE THREAD

**Issue by joshas** [ubuntu/gnome-shell-extension-appindicator#103]
Currently custom Dropbox context menu is broken: doesn't open on click, recently updated files submenu doesn't work. How about adding option to use native (QT) context menu, until Dropbox releases a fix? It already works by double clicking app indicator icon, but sometimes I get two menus - one QT and one GTK styled on top.

**Comment by jhasse** [comment]
See https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74. The workaround is to start Dropbox like this:

```
env XDG_CURRENT_DESKTOP=Unity dropbox start
```

> How about adding option to use native (QT) context menu

You'll get exactly that by using https://extensions.gnome.org/extension/1031/topicons/ :)
