### ISSUE TITLE
enhancement: only one icon on the panel

### ISSUE THREAD

**Issue by legluondunet** [ubuntu/gnome-shell-extension-appindicator#104]
Hello,
i don't need to see the icons in the systray all the time and depend your apps number placed in the systray, it could take a lot of space on the panel.
It could be great to add this feature: TopIcons-plus extension show only one icon on the panel, when you click on this icons you can see all the icons in the systray. It's a featrue request similar to the systray icons in Windows (you can partially hide them on WIndows).

LGDN.

**Comment by jhasse** [comment]
Thanks for reporting. I think this is the same as #76.
