### ISSUE TITLE
OpenPGP Applet - Legacy drawer

### ISSUE THREAD

**Issue by inverse** [ubuntu/gnome-shell-extension-appindicator#105]
OpenPGP Applet used to work on Ubuntu Gnome 17.04 due to the legacy drawer support. 

Since upgrading to 17.10 it's not functioning. Is it possible for this extension to revive this or would the applet need to be upgraded to handle such cases?

**Comment by jhasse** [comment]
You can get the legacy drawer back using [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/).

For the OpenPGP Applet to work with AppIndicator/KStatusNotifierItem, they would need to update their code. If they have a bug tracker, bring it up, most of the time it's quite an easy fix (as most apps already support AppIndicators for Unity).

**Comment by inverse** [comment]
Thanks for the heads up :+1:

**Comment by nodens** [comment]
Hi, just FYI, there is no appindicator support in openpgp applet. So for now. the solution is TopIcons. That said, a proper gnome extension is in the works (no ETA though, it means major code changes since there is no standalone app yet).
