### ISSUE TITLE
Clicking on Electron/Chrome notification causes Mega panel to open

### ISSUE THREAD

**Issue by domsle** [ubuntu/gnome-shell-extension-appindicator#108]
This bug is super weird.

Whenever I recieve any notification (native Gnome) by an electron app (Mailspring in my case), or by Chrome, and I click on it, it does its action as well as opening Mega synchronizaton client panel. This panel is accessible by double clicking Mega tray icon.

Mega needs to be running in the background.

**Comment by jhasse** [comment]
Could be the same bug as https://github.com/telegramdesktop/tdesktop/issues/1026

**Comment by 3v1n0** [comment]
Not related to the indicator, should be reported to the shell instead.
