### ISSUE TITLE
Jetbrains Toolbox Icon Size

### ISSUE THREAD

**Issue by katastrophal** [ubuntu/gnome-shell-extension-appindicator#109]
![bildschirmfoto von 2017-11-10 18-28-28](https://user-images.githubusercontent.com/2559413/32670749-0647a39c-c645-11e7-9ae9-9d8a256dd628.png)

The Icon Size of the [Jetbrains Toolbox](https://www.jetbrains.com/toolbox/app/) is tiny. This is on Fedora 27, latest gnome-shell (3.26.2) and latest extension from e.g.o

**Comment by justinnichols** [comment]
Confirmed, and this is with the latest 17.10.2 gnome-shell-extension-appindicator.  Telegram is also the same way (though not _quite_ as tiny).

**Comment by jhasse** [comment]
This is because the Ubuntu version is outdated, see #68.

**Comment by katastrophal** [comment]
wait what? I'm not even using Ubuntu! This is the version from extensions.gnome.org

**Comment by jhasse** [comment]
Sorry, missed that. Telegram at least should be fixed with the version on e.g.o.

**Comment by jhasse** [comment]
Jetbrains Toolbox size is correct with

```
env XDG_CURRENT_DESKTOP=Unity ./jetbrains-toolbox
```

so I'm closing this as a duplicate of #74.
