### ISSUE TITLE
22px icon size as standard

### ISSUE THREAD

**Issue by varlesh** [ubuntu/gnome-shell-extension-appindicator#112]
Reasons:
- Initially libappindicator write for Unity desktop and on Unity used 22px icon size as standard.
- Mostly applications use libappindicator and write for Ubuntu (with Unity Desktop) and not have other sizes
- Now extension broken compability for mostly popular apps (chrome, skype, telegram and etc)
- Also KDE (with QSystemTray) on Plasma used 22px icon size as standard for tray. It's will be cool have unification with Qt/KDE apps
- Mostly popular icon themes (and ubuntu-mono too) not have 16px status icons icons for apps
- 16px icon size have very small area and pixels - it's hard for design development

Why you don't want use 22px icon size as standard?

**Comment by jhasse** [comment]
Can you test if the latest master works for you?

16px is GNOME's icon size for the other icons in the panel, that's why we used that, too.

**Comment by morealaz** [comment]
Works for me with Arch Linux, and GNOME 3.26.2
extension installed from GitHub repo by [gnome-shell-extension-appindicator-git](https://aur.archlinux.org/packages/gnome-shell-extension-appindicator-git/) package.

![image](https://user-images.githubusercontent.com/2796369/33204303-5aafa690-d118-11e7-8e88-e265df0553f7.png)

thanks.

**Comment by varlesh** [comment]
> 16px is GNOME's icon size for the other icons in the panel, that's why we used that, too.

Really this icons used for gnome extensions only and have SVG-format with `-symbolic` suffix. 
But 3d-part apps (telegram, viber, psensor and more more others) not have yet.

**Comment by echonaut** [comment]
I would request reverting this change as it has caused icons in the top bar of GNOME become oversized and stretched and they just don't look very good. Compare the Slack and Discord icons to the wifi/sound/battery icons in GNOME:

![screenshot from 2017-12-07 12-46-23](https://user-images.githubusercontent.com/12798893/33732661-c2b5b43a-db4c-11e7-95c2-e7ba31939620.png)

**Comment by jhasse** [comment]
@echonaut Why did you remove your post? I think it was a valid concern.

**Comment by echonaut** [comment]
@jhasse because I realized this wasn’t the issue and I posted it in the wrong place. Turns out it was #110
