### ISSUE TITLE
Looking for a new maintainer (on e.g.o)

### ISSUE THREAD

**Issue by jhasse** [Ubuntu/gnome-shell-extension-appindicator#113]
I'm no longer using GNOME Shell (and therefore this extension) myself. If someone wants to take over, that would mean the ownership of https://extensions.gnome.org/extension/615/appindicator-support/ in particular.

**Comment by 3v1n0** [comment]
Hey, I'm already working on this extension to fix various issues and craft it, so my idea was to propose PRs soon, but if you've not time for this, I'll be happy to take over.

Cheers.

**Comment by jhasse** [comment]
Do you have an account on e.g.o?

**Comment by 3v1n0** [comment]
Yeah, same username I've here: `3v1n0`

**Comment by jhasse** [comment]
Okay nevermind, I can't give you ownership myself anyway. I think you'll have to write to the GNOME Shell mailing list and point them to this issue ;)

**Comment by maweki** [comment]
One of us will do the transfer within one or two days.

**Comment by 3v1n0** [comment]
Thanks @maweki.
