### ISSUE TITLE
Not support "wine system tray"

### ISSUE THREAD

**Issue by lzp4ever** [Ubuntu/gnome-shell-extension-appindicator#118]
wine system tray display separately.
Its supported in top icon plus.

**Comment by jhasse** [comment]
Wine needs to support the AppIndicator/StatusNotifierItem API for this.

**Comment by pacho2** [comment]
Just for informing other people like me trying to know about how to get wine/crossover notifications shown, this is the upstream bug
https://bugs.winehq.org/show_bug.cgi?id=38409
