### ISSUE TITLE
After the latest commits on April 4th, the git version no longer works

### ISSUE THREAD

**Issue by Taijian** [ubuntu/gnome-shell-extension-appindicator#129]
I am running Gnome 3.28 on Arch (X11) and the git version no longer works (as in: Gnome-tweak-tools does not recognize the extension as installed, so I cannot activate it and it also does not do anything).

**Comment by repsac-by** [comment]
broken  `metadata.json`
there is an extra comma in the last line

**Comment by Taijian** [comment]
thank you, that worked!

**Comment by 3v1n0** [comment]
Sorry, fixed. Use `git pull --rebase origin master` if already use this tree, though.
