### ISSUE TITLE
[Feature] color desaturation and transparancy 

### ISSUE THREAD

**Issue by arigit** [ubuntu/gnome-shell-extension-appindicator#142]
This is a great extension (I had stability issues with topicons+ for years, crashing the shell after suspend), the one feature I miss (from topicons plus) is:

support to set a global tray icon de-saturation %, and a global tray icon transparency (or brighness)

This feature really help blend old applications with shiny tray icons into the modern, "materials-style" desktop of today. It doesn't fix the design problem in those older apps but this greatly mitigates the visual annoyance.

Hoping this can be added to this extension, as topicons+ used to have

**Comment by Finii** [comment]
To fix this, I added the (hard coded) possibility to specify de-saturation, transparency, brightness, and contrast. You would have to pick your values and plug them in. This is in my [fork branch feature/add_desaturation](/Finii/gnome-shell-extension-appindicator/tree/feature/add_desaturation) (Finii/gnome-shell-extension-appindicator@d376cafd4110d865f18e483881eb417615c74d7a)

This is ok-ish if one is willing to do manually adjust things. Just clone that branch and put the files in `~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/`

Further I started to pull the settings dialog over and update the values on the fly. This is not finished. Help appreciated. Find the [fork branch feature/add_settings](/Finii/gnome-shell-extension-appindicator/tree/feature/add_settings) (Finii/gnome-shell-extension-appindicator@be363c88124d41c173586570c407a355ccb1b077)
