### ISSUE TITLE
Skype appindicator is missed with "Gnome on Xorg" session

### ISSUE THREAD

**Issue by ant-** [ubuntu/gnome-shell-extension-appindicator#152]
Steps to reproduce: 
1. Install gnome-themes-standart, gnome-session, vanilla-gnome-desktop.
2. Log out.
3. On the login screen choose "Gnome on Xorg" and login.
4. Run skype.

gnome-shell-extension-appindicator         18.04.1
Ubuntu 18.04
GNOME Shell 3.28.3

**Comment by tapir** [comment]
On arch linux I don't see and indicator for skype as well

**Comment by 3v1n0** [comment]
This is should be not a bug if you didn't install this from extensions.gnome.org in the gnome on xorg session. Did you?

**Comment by ant-** [comment]
I've tried both: install extension from gnome-shell-extensions site, and ubuntu-appindicator.
