### ISSUE TITLE
It stopped working in Gnome 3.30?

### ISSUE THREAD

**Issue by jecogeo** [ubuntu/gnome-shell-extension-appindicator#153]
I noticed all app indicators disappeared after a system update (Manjaro Linux) some weeks ago. And nothing I did until now worked. Gnome is nos supporting this extension anymore?

**Comment by pwd-github** [comment]
It works fine on Ubuntu and Fedora. Have you Alt+F2 and Restarted?

**Comment by balthild** [comment]
Not working on Arch Linux as well.

**Comment by rene-s** [comment]
I am running Gnome 3.30.2 on Arch and it's working.

**Comment by fernandocollova** [comment]
@pwd-github can I ask you on which Fedora version? Because I'm running fedora 29, and the extension doesn't work on either Xorg or Wayland.

**Comment by fernandocollova** [comment]
Also, in case this is related, [Toopicons Plus also stopped working since Fedora 28](https://bugzilla.redhat.com/show_bug.cgi?id=1573771)

**Comment by pwd-github** [comment]
@fernandocollova 
`
     :-----------/shhOHbmp---:\       OS: Fedora 29 (Workstation Edition) x86_6 
   /-----------omMMMNNNMMD  ---:      Host: 80DU Lenovo Y70-70 Touch 
  :-----------sMMMMNMNMP.    ---:     Kernel: 4.20.6-200.fc29.x86_64 
 :-----------:MMMdP-------    ---\    Uptime: 20 hours, 7 mins 
,------------:MMMd--------    ---:    Packages: 2017 (rpm) 
:------------:MMMd-------    .---:    Shell: bash 4.4.23 
:----    oNMMMMMMMMMNho     .----:    Resolution: 1920x1080 
:--     .+shhhMMMmhhy++   .------/    DE: GNOME 3.30.2 
`

**Comment by fernandocollova** [comment]
Did you install any dependencies? I installed `libappindicator` just because it seemed like a good idea, but I'm not familiar with what this extension might need.

**Comment by pwd-github** [comment]
@fernandocollova No. Why would you install that? What I will say though, if neither are working no matter what, you're probably locked into a Wayland session.

Are you using a Nvidia graphics card by chance?

**Comment by milankni** [comment]
Installing libappindicator-gtk3 (+ few dependencies) on Arch Linux made a difference. This extension works again!
(I grepped package manager log and there was no install/uninstall of "libapp" in the past two years. Something must have changed in Gnome Shell packaging / dependencies, then.)

**Comment by fernandocollova** [comment]
@pwd-github No, not at the moment. I do have an hybrid graphics setup, but I just confirmed with `lsmod` that neither `nouveau` or `nvidia` are loaded, just i915.

And, I installed `libappindicator` because, as @milankni pointed, I remember it was part of what I did to make this extension work in the past, in another install of Fedora 28.

Now I'm installing 29 on a new laptop, and I'm not saying the install played any part on solving the issue back then, but my foggy memory from months ago said it was part of making this extension work, so I figured installing it won't hurt anyone.

**Comment by rnhurt** [comment]
Just upgraded Pop!_OS to Gnome 3.30.2 and discovered the this extension stopped working.  I uninstalled and tried to reinstall it but the Gnome Shell Extensions website just shows a red ERROR.  :frowning:

**Comment by elpraga** [comment]
After the upgrade of the extension it stopped working showing a big red ERROR. Ubuntu 18.10, Gnome 3.30.1. It used to be working fine until the upgrade. 

No other changes made. I was working fine before the upgrade

**Comment by jalefkowit** [comment]
I'm hitting the same issue as @rnhurt and @elpraga -- tried to update via extensions.gnome.org, got a big red "ERROR" with no further information, extension stopped working. Tried uninstalling and reinstalling but got the same red ERROR. I'm on Ubuntu 18.10, GNOME 3.30.1.

**Comment by TeamLinux01** [comment]
I updated the extension this morning and it stopped working, too.
Running Pop!_OS 18.10.

**Comment by curvatura99** [comment]
Extension stopped working on two different  computers both running Ubuntu 18.10 with Gnome 3.30.2. Manually installed the previous version until this error gets sorted.

**Comment by elpraga** [comment]
I'm sorry @curvatura99 it might seem a silly question, but could you give a hint how to manually install the previous version?

**Comment by curvatura99** [comment]
> I'm sorry @curvatura99 it might seem a silly question, but could you give a hint how to manually install the previous version?

Go to the extensions page (https://extensions.gnome.org/extension/615/appindicator-support/) and download shell 3.26 version 22.

Open a terminal and go this extension in your home directory:
`cd  ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/`

Delete all the files in that folder:
`rm -rf *`

Unzip the file you downloaded into the same directory:
`unzip appindicatorsupport@rgcjonas.gmail.com.v22.shell-extension.zip -d ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com`

Logout and login to Gnome for the extension to reload. If you have Gnome Shell Extension Reloader installed (https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/) you can reload without logout/login.

All of this can be done through the Nautilus file manager if you prefer.

**Comment by elpraga** [comment]
Thank you @curvatura99 ! Using the old version worked!

**Comment by 3v1n0** [comment]
New updated version should work now.

Also see https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/166#issuecomment-477397315
