### ISSUE TITLE
Applications menu in GS 3.30.1 is gone after an upgrade (3.31.4-2)

### ISSUE THREAD

**Issue by dino99** [ubuntu/gnome-shell-extension-appindicator#156]
This is with Ubuntu Disco (19.04) on a gnome-shell on xorg session.
A couple minutes after upgrading gnome-menus 3.31.4-2ubuntu1 (proposed archive) , the Apllications menu on top left bar has gone, and journalctl shows:

Extension "apps-menu@gnome-shell-extensions.gcampax.github.com" had error: GLib.MarkupError: Error on line 241 char 10: Element “Menu” was closed, but the currently open element is “Exclude”

Package reference is:
gnome-shell-extension-appindicator (22-1) unstable; urgency=medium

  * Initial release (Closes: #898144)

 -- Matteo F. Vescovi <mfv@debian.org>  Mon, 07 May 2018 23:37:59 +0200

**Comment by jbicha** [comment]
This was a [gnome-menus issue](https://gitlab.gnome.org/GNOME/gnome-menus/issues/9) and a fix was just pushed to Ubuntu 19.04 (it will take some time to build and be published). Please close this issue.

**Comment by dino99** [comment]
Thanks for the quick fix
