### ISSUE TITLE
Out of proportions in HIDPI displays

### ISSUE THREAD

**Issue by ArtificialAmateur** [ubuntu/gnome-shell-extension-appindicator#158]
Icons are completely distorted and out of proportion on HIDPI 4k display.

Kstatusnotifieritem:
![kstatusnotifieritem](https://user-images.githubusercontent.com/20297606/52074522-fac90e00-2581-11e9-8a90-32d7bb354ed8.png)

TopIconsRedux:
![topiconsredux](https://user-images.githubusercontent.com/20297606/52074631-38c63200-2582-11e9-8453-24b5867f8085.png)

**Comment by hexchain** [comment]
See #110, looks like it's already fixed in git master, but there is no release yet.

**Comment by BHSPitMonkey** [comment]
Do releases to extensions.gnome.org still actually happen? It looks like there were no tags created in all of 2018, despite a fair amount of changes on master.
