### ISSUE TITLE
TypeError: GObject.registerClass() used with in valid base class (is PanelMenuButton)

### ISSUE THREAD

**Issue by isjerryxiao** [ubuntu/gnome-shell-extension-appindicator#161]
After upgrading to https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/f7d9118903ff081858b92f2bc20e4ba789c4852a, I got  
`gnome-shell[893]: Extension "appindicatorsupport@rgcjonas.gmail.com" had error: TypeError: GObject.registerClass() used with in
valid base class (is PanelMenuButton)`  
in my journal and the extention errors out in gnome-tweaks.

Os: Archlinux
Gnome shell version: 3.30.2,  using gnome on xorg

**Comment by 3v1n0** [comment]
Mhmh, I think this is due to the fact you're running in 3.30, so there's no other fix than removing that version from the supported ones, while it will work in 3.32 properly.
