### ISSUE TITLE
Why remove 3.30 support

### ISSUE THREAD

**Issue by Sherlock-Holo** [ubuntu/gnome-shell-extension-appindicator#162]
in gnome official web site [news](https://www.gnome.org/news/), the latest stable version is 3.30, [wikipedia](https://en.wikipedia.org/wiki/GNOME) says the preview version is 3.31.90 (6 February 2019), so if 3.30 is still stable version why remove the support

**Comment by 3v1n0** [comment]
Because 3.32 is going to be released in few days, so upstream code here stays in sync with what upstream gnome-shell is using.

For previous versions, previous extension versions should be used.
