### ISSUE TITLE
Any debugging advice

### ISSUE THREAD

**Issue by davidbannon** [ubuntu/gnome-shell-extension-appindicator#163]
I just tried this extension in a new install of Fedora29 and no luck.
I pulled down zip file from github, symlinked its directory as per instructions, ran the gnome extension tool. Good to that point.
Next I did the Alt-F2-r-<enter> but was told that a restart is not available in Wayland, so restarted the session.
Then tried tomboy-ng (my app) from https://github.com/tomboy-notes/tomboy-ng but see no [appindicator|systray] icon.

tomboy-ng uses the old school GTK2 SystemsTray model, perhaps I am being too hopeful ?

Are there logs dropped somewhere, maybe some way of confirming the extension itself is OK but my app not doing whats needed ?

Davo

**Comment by 3v1n0** [comment]
Systray model isn't supported by this extension. TopIcons might work for this, but we won't support old systray icons here.

If you can use libappindicator in your app to support both mode would be great.

**Comment by davidbannon** [comment]
Thanks 3V, my app tries to use the (Unity inspired) libappindicator3 and failing that falls back to using libappindicator (which I call System Tray, maybe incorrectly ?). Its all handled by the Lazarus libraries which provides the widgets.

I can trace the actual GTK system calls involved in either case if that would help clarify what I'm using and, perhaps, help me implement something that does work with some long term supported model ?
Or you can point me to the system calls you consider an app should be using ?

I need to end up with an Icon on the top or bottom toolbar that, when clicked, can display its menu. The look and feel may be old fashioned and greatly offend the Gnome Developers but its what users want ....

Davo

**Comment by 3v1n0** [comment]
Well, I'm not familiar with those libraries, what you need to have here is just to have something that implements the [StatusNotifierItem](https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/interfaces-xml/StatusNotifierItem.xml) dbus protocol.

A simple gobject implementation is at https://github.com/jjk-jacky/statusnotifier

**Comment by davidbannon** [comment]
Thanks 3v1n0, I'll chase those links up.

I'll close this ticket, thanks for your help.

David
