### ISSUE TITLE
Icons too big since v23

### ISSUE THREAD

**Issue by bernimoses** [ubuntu/gnome-shell-extension-appindicator#167]
Since the extension update to v23 the panel icons are too big.
![Screenshot from 2019-04-02 17-40-48](https://user-images.githubusercontent.com/239049/55416140-8c4b0100-556e-11e9-8f79-4d67fcc8998f.png)
If i remove the `+ 6` from https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/indicatorStatusIcon.js#L40 which i think is because of legacy / compatibility reasons it looks fine.
![Screenshot from 2019-04-02 17-40-11](https://user-images.githubusercontent.com/239049/55416246-b7cdeb80-556e-11e9-80b2-ab8a028ec815.png)
Is this something we can remove / change back?

**Comment by 3v1n0** [comment]
This is in 3.32, right?

**Comment by bernimoses** [comment]
Oh sry, yes 3.32.0

**Comment by elwerene** [comment]
I can confirm the fix from @bernimoses works. But I guess it was there for a reason. Can you check for the installed gnome shell version and add the `+6` prior to 3.32.0?

**Comment by 3v1n0** [comment]
This is now fixed as per commit 8b8455906f2b126031e5899e2b3e7ce6c247cab7
