### ISSUE TITLE
Not honoring text scaling factor: icons too small

### ISSUE THREAD

**Issue by memeplex** [ubuntu/gnome-shell-extension-appindicator#181]
I've a hidpi screen but I use it with a scale factor of 1 (since 2 would be too much, the resolution is not that high) and up-scaled fonts. The icons in the appindicator extension are slightly smaller than the surrounding icons in the top bar. Changing this:

```
this._iconBox = new AppIndicator.IconActor(indicator, Panel.PANEL_ICON_SIZE + 6);
```

to 

```
this._iconBox = new AppIndicator.IconActor(indicator, Panel.PANEL_ICON_SIZE + 12);
```

fixes the issue in an ugly way.

**Comment by memeplex** [comment]
I think this is due to the fact that the text has been scaled up. PANEL_ICON_SIZE is equal to 16  but other icons in the top bar are clearly larger than that (about 20 pixels). PANEL_ICON_SIZE is probably a constant that doesn't get updated when the font is scaled.

**Comment by memeplex** [comment]
Indeed I have been debugging this and the problem is that every other icon is properly scaled by the text scaling factor but appindicator icons aren't. i think you should scale icons based on the geometry assigned to the extension instead of starting from PANEL_ICON_SIZE.

**Comment by memeplex** [comment]
Or maybe you should set some kind of expand = true when adding the icon to its container?

**Comment by memeplex** [comment]
Now I'm using a 3000x2000 screen at 2x scale factor and 1x font scaling factor and, on the contrary, I had to set `Panel.PANEL_ICON_SIZE + 2`. This badly needs to be configurable or smarter. Configurable seems easier though.

**Comment by memeplex** [comment]
Thanks Marco!

**Comment by Saviq** [comment]
FWIW on my LoDPI screen it does't all look that great with [the package from Debian](http://deb.debian.org/debian/pool/main/g/gnome-shell-extension-appindicator/gnome-shell-extension-appindicator_33-1_all.deb):

![obraz](https://user-images.githubusercontent.com/231077/77316017-e48f8b80-6d08-11ea-8276-2320f18ffac6.png)

The icons are quite a bit smaller than they used to be (too small?). Not sure what the ellipsis is, it doesn't seem to do anything.

**Comment by jarrard** [comment]
Sadly these changes did not resolve my problem, I have the icons being quite small. And with font scaling up to 1.50. 

Using Pop!_OS atm.
