### ISSUE TITLE
OBS and Chrome icon not shown

### ISSUE THREAD

**Issue by BjoernDaase** [ubuntu/gnome-shell-extension-appindicator#183]
I have a fresh install of the Ubuntu 19.10 daily build with the built in appindicator extension.

Sadly, some tray icons aren't displayed, e.g the tray icon of Chrome and OBS.
On the other hand, the most icons, e.g. of Skype, Mailspring, Telegram and Franz are displayed in the tray.

**Comment by veyselerden** [comment]
Try this: `sudo apt install libappindicator1 libappindicator3-1`

I was having issues with having the Lantern app to display its indicator, this has solved it for me.

**Comment by BjoernDaase** [comment]
I switched over to Fedora a while ago and still use this extension (but now as a regular extension).  

1. I never had a problem with the OBS icon again, that always shows up perfectly fine for me.
2. The Chrome still does not show up. But I think that is a Chrome problem that it does not run in the background even though the option is checked in the settings, top lists no more Chrome instances after closing it. 

So I think this issue can be closed.
