### ISSUE TITLE
icon theme not honoured

### ISSUE THREAD

**Issue by rudrab** [ubuntu/gnome-shell-extension-appindicator#184]
Hi,
I just moved from `topicon plus` to here.
One thing I see is neither topicon nor this app honours customed theme icons. 
Is this a issue related to DE itself (I am using gnome 3.32 in fedora 30)

**Comment by Netroxen** [comment]
I believe this has to do with some applications using hard coded icons for the app indicators. In this case it's not possible to override the icon in the tray area.

Someone correct me if I'm wrong...

**Comment by rudrab** [comment]
That is one case, I agree. For desktop icons, I edit the corresponding `.desktop` file. Any idea what to do for this case?

**Comment by 3v1n0** [comment]
> I believe this has to do with some applications using hard coded icons for the app indicators. In this case it's not possible to override the icon in the tray area.
> 
> Someone correct me if I'm wrong...

This is indeed the case, we can't theme such icons that are provided by the app.
There's not much to do with this, unless changing the apps themselves.

If they use a named icon, we indeed theme them.
