### ISSUE TITLE
Dropbox menu for "select folders" button is not triggered

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-extension-appindicator#189]
This worked find before, not sure if that is a Dropbox client issue, or related to GNOME and or this extension.

[Dropbox Forum](https://www.dropboxforum.com/t5/Installs-integrations/Debian-10-1-gt-Cannot-choose-folders-to-sync/td-p/364023)

**Comment by 0xA1B2** [comment]
Got fixed by new Dropbox release.

**Comment by jhasse** [comment]
Please reopen if you can still reproduce with the newest Dropbox version.
