### ISSUE TITLE
Enable icon identification

### ISSUE THREAD

**Issue by kenperkins** [ubuntu/gnome-shell-extension-appindicator#191]
I have an icon in the app indicator area but I don't know what it belongs to. Is there a way to enable identification of which icon goes to which application?

ps my unknown icon: https://i.imgur.com/TKdbAPB.png

**Comment by kenperkins** [comment]
For what it's worth, discovered that the icon in question is for Quassel IRC client.

**Comment by JasonLG1979** [comment]
A tooltip would do the trick. See [indicatorToolTip](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/blob/master/mprisindicatorbutton%40JasonLG1979.github.io/indicatorToolTip.js) for an implementation of a base class that's stupid simple to extend.

**Comment by 3v1n0** [comment]
You can do it using gnome shell looking glass (alt+f2 -> lg -> enter)
https://wiki.gnome.org/Projects/GnomeShell/LookingGlass
