### ISSUE TITLE
Microsoft Teams for Linux Icon missing on 3.34

### ISSUE THREAD

**Issue by lenuswalker** [ubuntu/gnome-shell-extension-appindicator#194]
Microsoft Teams for Linux Icon is missing in the tray.

**Comment by vlastoun** [comment]
Topicon plus does display teams icon

**Comment by csurett** [comment]
Works for me on 3.34.3 using the official teams RPM on Fedora 31

**Comment by dluuugi** [comment]
It's not working for me on GNOME 3.34.4 (Teams version 1.3.00.958, not from flatpack).

**Comment by BreadyX** [comment]
On my laptop the icon is not showing (Teams version 1.3.00.958 installed from official RPM on Fedora 31). On my desktop (Teams version 1.3.00.958 installed from official RPM on Fedora 31), however, the icon is showing as it should be.

**Comment by jhasse** [comment]
I guess Microsoft Teams for Linux is using Electron?

**Comment by BreadyX** [comment]
AFAIK yes. But Discord (another Electron app) has no problem.

**Comment by jhasse** [comment]
Is there a way to find out which Electron version they are using? The support got improved in Electron 8.

Anyway: There's nothing we can do about this (besides very ugly workarounds). This really needs to be fixed by Microsoft Teams.

**Comment by ks1322** [comment]
On Fedora this extension is not installed by default. It should be installed with `sudo dnf install gnome-shell-extension-appindicator` and then enabled.
