### ISSUE TITLE
Add note about dependencies in README

### ISSUE THREAD

**Issue by FernandoBasso** [ubuntu/gnome-shell-extension-appindicator#195]
Perhaps it would be useful to add a note in the readme about dependencies for this extension.

On Arch Linux, it started working after I installed libindicator stuff and restarted the shell.

```
$ pacman -S libindicator-gtk{2,3} lib32-libindicator-gtk{2,3} --needed
```

**Comment by jhasse** [comment]
Please add that info the wiki: https://github.com/ubuntu/gnome-shell-extension-appindicator/wiki

But to be pedantic: The extension works without those packages. It's some apps that need those.
