### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by PiiNGPooNG** [ubuntu/gnome-shell-extension-appindicator#205]
I'm stepping into controversial territory here, but I'm taking that risk. This obviously links back to #68 like pretty much any other issue regarding this topic.

Now onto my opinion about this issue. I can't comprehend why 22px is the default icon size and not 16px. Why do I think they should be 16px? My reasons are that the system icons are also 16px (in most cases as far as I know), 22px can make icons look blurry, and why would you want to have tray icons almost as big as active/open/pinned application icons?

16px: (Icons are Telegram, Dropbox, Mailspring, Synergy)
![16px](https://user-images.githubusercontent.com/8688059/75626395-8bc84980-5bc7-11ea-80f0-4d0bd4daca89.png)
22px:
![22px](https://user-images.githubusercontent.com/8688059/75626396-8cf97680-5bc7-11ea-8d82-c4078c39c3e6.png)

All icons feel like they get blurry to me (except Synergy, because that already is really blurry in 16px).
There's also some weird spacing going on between Telegram and Dropbox with 22px (that might just not be noticeable on 16px)

The 16px in my example here is achieved by adding "- 6" to this line:
 https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/b15e8138392f94ec7fa32f1233aefafbcaf09983/appIndicator.js#L290

Changing this to 16 didn't work, but I didn't try to figure out all code to know why:
https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/b15e8138392f94ec7fa32f1233aefafbcaf09983/appIndicator.js#L36

Ideally, #200 would solve this. Everybody can easily adjust the size to their liking and if done correctly the sizing would carry over when updating the extension. However, I, for one, would prefer 16px to be the standard.

**Comment by spielkind** [comment]
With the changes in 8b84559 I got following "issue":
Icons look a bit to small:
![new-to-small](https://user-images.githubusercontent.com/4437264/76561448-99bd7a80-64a3-11ea-9b34-3c7b49914256.png)

With the old version this looks better:
![old-fixed-correct-size](https://user-images.githubusercontent.com/4437264/76561447-9924e400-64a3-11ea-913f-4461396763f2.png)

(In the old version I fixed the icon size with: https://github.com/bilelmoussaoui/Hardcode-Tray) I also tried to revert this, but the icons now have do not look streched, but still too small.

**Comment by 3v1n0** [comment]
> With the changes in [8b84559](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/8b8455906f2b126031e5899e2b3e7ce6c247cab7) I got following "issue":
> Icons look a bit to small (keybase, slack, rambox):
> ![new-to-small](https://user-images.githubusercontent.com/4437264/76561448-99bd7a80-64a3-11ea-9b34-3c7b49914256.png)
> 
> With the old version this looks better:
> ![old-fixed-correct-size](https://user-images.githubusercontent.com/4437264/76561447-9924e400-64a3-11ea-913f-4461396763f2.png)
> 
> (In the old version I fixed the icon size with: https://github.com/bilelmoussaoui/Hardcode-Tray) I also tried to revert this, but the icons now have do not look streched, but still too small.

This is actually a "feature". The app-indicators were way too big compared to the shell default icons, and this was wrong both visually and conceptually.

So, you can hack that by changing the `icon_size` property or setting the style `icon-size` css parameter on the icon.

So, feel free to change this but, until we don't provide settings (patches welcome!), we need to default to the shell-preferred icon size.

What we may indeed tune is the margin though.

**Comment by spielkind** [comment]
Even compared to the "original" icons or the "bing wallpaper extension icon) the appindicator icons look a bit to small. :/ 
I've seen that @Finii is working on a preferences patch, where everyone could tune this setting for his personal gusto.

**Comment by Finii** [comment]
Sorry, with the latest rebase on master my PR lost the ability to change the icon size.
If this is really an issue (I feel not like that) and Corona homeoffice prevails I might find time to add it in again, but atm not planning that. Ppl should try the new master and re-request the feature if they like it. I personally lost the need for resizing with the recent changes.

**Comment by Finii** [comment]
Size settings enabled again in my PR #196.
