### ISSUE TITLE
GNOME 3.36 icon sizes

### ISSUE THREAD

**Issue by v4rakh** [ubuntu/gnome-shell-extension-appindicator#208]
Some icon sizes seem a little bit off when using the latest GNOME 3.36. The same icons were just fine with 3.34.

![Screenshot-2020-03-08-202459](https://user-images.githubusercontent.com/55667263/76169702-cce5ce00-6172-11ea-8c26-53cbf84647cb.png)

Scaling is at default of 1,0

**Comment by adaigre** [comment]
Same thing here on a recently updated Arch.
Note that I have set text scaling factor to 1,25 in GNOME Tweaks.

**Comment by fdinardo** [comment]
I have the same problem. To Be honest event the with gnome 3.34 I noticed that, but the difference was really small maybe 1-2 px. 
Now with the new Gnome version (3.36) this issue has been huge... 
Here an image:
![image](https://user-images.githubusercontent.com/7387557/76230589-307c0400-6224-11ea-9056-64b10d9d81cd.png)

Slack, Dropbox and Flameshot are bigger than the other "native" icons. Dropbox goes outside the panel as well, slack has been cut off.

Hope this will help. 
Thanks

**Comment by v4rakh** [comment]
@3v1n0 Thanks! Is there an ETA how long it will take to get released with those fixes?

**Comment by fdinardo** [comment]
@3v1n0 
This is great, I just tested the master branch today!
here is the result:
![image](https://user-images.githubusercontent.com/7387557/76619961-6a068500-652c-11ea-8f8d-3dedf1f86e4e.png)
Thank you for your work. This is amazing!
