### ISSUE TITLE
Not working properly in Gnome3.36

### ISSUE THREAD

**Issue by moon-zhangzexi** [ubuntu/gnome-shell-extension-appindicator#210]
These icons are stretched in some themes
![image](https://user-images.githubusercontent.com/57009175/76483154-399de880-6451-11ea-82ef-d349866a783c.png)

Gnome 3.36

**Comment by willydee** [comment]
I can confirm stretching issues with _some_ but not all icons. Particularly, the SVG icon of the JetBrains Toolbox app is distorted, see screenshot. On my desktop, the behavior is only shown in conjunction with the Dash to Panel extension.

![Screenshot from 2020-03-12 11-17-53](https://user-images.githubusercontent.com/7428576/76511229-2724ae80-6453-11ea-98f8-166bea7c1eba.png)

**Comment by chr-debhl** [comment]
Same thing was happening with the Nextcloud icon, and current `master` seems to have fixed that issue. Could you maybe try it and report back?

**Comment by willydee** [comment]
LGTM.

![Screenshot from 2020-03-12 14-57-03](https://user-images.githubusercontent.com/7428576/76528880-cc4e7f80-6471-11ea-933e-cff7e0bc3997.png)

**Comment by 3v1n0** [comment]
Great, thanks for testing!

Fixed by commit 8b8455906f2b126031e5899e2b3e7ce6c247cab7
