### ISSUE TITLE
Difficult to navigate to submenus when the menu is too long

### ISSUE THREAD

**Issue by Saviq** [ubuntu/gnome-shell-extension-appindicator#218]
**Describe the bug**

The Multipass indicator lists all the VMs I have used. I want to shell into one. I find it in the list and hit the triangle. It opens up a small section which I need to scroll to find the "Shell" option.

**To Reproduce**
1. Have 27 VMs created with multipass
1. Set screen to 1080p on GNOME Shell
1. Try to get to the shell option for the bottom VM

You get a tiny tiny scroll bar and it's very hard to use.

![Screenshot from 2020-03-25 09-25-35](https://user-images.githubusercontent.com/1841272/77529074-e2533b80-6e86-11ea-9f26-ded6d7b2452d.png)

**Expected behavior**
A menu to appear, from which I could choose "Shell"

_originally reported by @popey in https://github.com/canonical/multipass/issues/1444#issue-587609317_

**Comment by jhasse** [comment]
If I'm not mistaken, this is a limitation by GNOME Shell bug, or rather its St toolkit. You can open an issue [at their bug tracker](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues), but I wouldn't expect a fix any time soon.

**Comment by Saviq** [comment]
Filed as https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2569 then.
