### ISSUE TITLE
Electron 8 icon disappears on reload (f. i. Signal-Desktop)

### ISSUE THREAD

**Issue by mandree** [ubuntu/gnome-shell-extension-appindicator#220]
Turning this into a new issue.
Issue #75 is back since Electron has updated to 8.x, for instance, Signal-Desktop 1.32.x. 

The icon is shown (IMO too small), but on reloading the shell, or lock screen/unlock, Signal's icon is gone. Specifically, see this comment on the closed issue. 
* https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/75#issuecomment-598041418
* https://github.com/signalapp/Signal-Desktop/issues/4082
* https://github.com/electron/electron/issues/22443

**Comment by jhasse** [comment]
For screen lock/unlock GNOME would have to fix https://bugzilla.gnome.org/show_bug.cgi?id=781760

To also fix reloading GNOME Shell (or reloading the extension) Chromium would have to fix https://bugs.chromium.org/p/chromium/issues/detail?id=1042098

**Comment by mandree** [comment]
@jhasse I think the changes of GNOME fixing their 781760 are near zero, especially after reading the chromium issue you referred to, comments #9 and #10 seem relevant but I cannot judge about their truth https://bugs.chromium.org/p/chromium/issues/detail?id=1042098#c9 - but given that other systems (for instance Plasma/KDE5) are less sensitive to losing the icons, pointing fingers at GNOME isn't implausible.

One final question: the assumption is that if chromium 1042098 were fixed, your assumption is that Electron would inherit the fix?

**Comment by jhasse** [comment]
Yes. Electron uses Chromiums tray implementation on Linux since version 8 IIRC. They don't add any libappindicator magic themselves.
