### ISSUE TITLE
A way to group icons, or decrease spaing between icons?

### ISSUE THREAD

**Issue by aasutossh** [ubuntu/gnome-shell-extension-appindicator#223]
So for decreasing icon gap there is https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/ as mentioned in #219 #217 .
Is there a way to group them? Or does it seem like unnecessary hassle?

**Comment by jhasse** [comment]
Not yet, see #76.

**Comment by aasutossh** [comment]
Cool. THanks.
