### ISSUE TITLE
Indicators from apps launched during startup doesn't appear

### ISSUE THREAD

**Issue by rastersoft** [ubuntu/gnome-shell-extension-appindicator#235]
When an application is set to be launched during startup, the icon doesn't appear in kstatus. Disabling and enabling it, or closing the application and relaunching it again fixes it.

**Comment by weeman1337** [comment]
Hey, it looks like that didn't work as expected.

Here is a link to a related launchpad issue: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1846944

For me running ubuntu 20.04 with the latest extension version the startup applications are still missing.
