### ISSUE TITLE
Huge lag spikes

### ISSUE THREAD

**Issue by hodasemi** [ubuntu/gnome-shell-extension-appindicator#236]
Hi, 

I'm on Manjaro, Gnome shell 3.36.2. Only when talking in Discord I get huge lag spikes. If anyone else in the channel talks its just fine. The log output:

`Mai 06 09:06:50 michael-pc appindicatorsupport@rgcjonas.gmail.com[1968]: discord1, Impossible to lookup icon for 'discord1_11-panel'
Mai 06 09:06:50 michael-pc gnome-shell[1968]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                              _createIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                              _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                              _updateIconByType@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                              _updateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                              _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:220:22
                                              _onPropertiesChanged@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:15
                                              refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19`

This is repeated multiple times every time I make a noise.

**Comment by Edexiel** [comment]
Seems related to #226, we are discussing possible temporary fix there.

**Comment by hodasemi** [comment]
Yea, seems to be the same issue. I have tested it on RTX2060 (using nvidia 440 driver), RX470 (mesa 20) and integrated intel. This problem only occurs on the proprietary nvidia driver. 
Maybe this information helps.

**Comment by notcdk** [comment]
Can reproduce, fedora 32, gnome 3.36, extension version is 33 so the latest from gnome extensions.gnome.org, amdgpu drivers, mesa 20.0.6
AMD NAVI10 (DRM 3.36.0, 5.6.11-300.fc32.x86_64, LLVM 10.0.0)
`May 13 23:07:15 cdk-pc appindicatorsupport@rgcjonas.gmail.com[1716]: discord1, Impossible to lookup icon for 'discord1_215-panel'
May 13 23:07:15 cdk-pc gnome-shell[1716]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                          _createIconByName@/home/cdk/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                          _cacheOrCreateIconByName@/home/cdk/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                          _updateIconByType@/home/cdk/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                          _updateIcon@/home/cdk/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                          _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                          _onPropertiesChanged/<@/home/cdk/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:220:22
                                          _onPropertiesChanged@/home/cdk/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:15
                                          refreshPropertyOnProxy/<@/home/cdk/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19
`

**Comment by derbrachialist** [comment]
same problem

**Comment by Edexiel** [comment]
Switched to TopIcon Plus, tired of no one maintaining this repo. Works great

**Comment by derbrachialist** [comment]
Worked thanks!

**Comment by 3v1n0** [comment]
This is fixed by commit 745c66a73e0a15a870e92e5aa461e2e9e646b899
