### ISSUE TITLE
App Indicators Override Flatpak "Run On Background Permissions"

### ISSUE THREAD

**Issue by alex285** [ubuntu/gnome-shell-extension-appindicator#239]
I copy paste the bug report from Flatpak related issue https://github.com/flatpak/xdg-desktop-portal/issues/491

## Description of the problem
When Ubuntu App-Indicators extension is enable,  Telegram keeps running when close from [x], even if the "Running in background" permission is off; 

## Reproduce
1. Enable App Indicators Extension
2. Open GNOME Settings, and from Applications -> Telegram, disable the "Run in Background"
3. Open Telegram
4. Close Telegram from [x]

**Outcome:** Telegram will still keep running on background (and also on Indicator)
**Expected:** The app should quit

**Comment by 3v1n0** [comment]
Mmh, I don't think this extension is the guilty here, but flatpak should not allow the application to export the interface instead.
