### ISSUE TITLE
size and padding issue / use with topicon / looking for manual override

### ISSUE THREAD

**Issue by squalou** [ubuntu/gnome-shell-extension-appindicator#246]
There are already some issues raised about size issues, none of which completely cover my case.
So let me expose it.

I'm using ubuntu 20.04 with gnome 3.36, and deactivated ubuntu appindicator to have a chance to play with icon sizes.

I'm using Dash to panel to avoid the top bar + dash (I care about my screen space)

I'm also using TopIconPlus extension, for some other apps that otherwise are not displayed (and the contrary is true too, so I need both)

For instance, here is it with **only topicon**

![image](https://user-images.githubusercontent.com/4623644/86515885-9cf6c080-be1c-11ea-841a-0f04c9bca11a.png)

Now **when I enable appindicator** :  (same result wit KStatus... from gnom extension and native ubuntu included one)

![image](https://user-images.githubusercontent.com/4623644/86515862-720c6c80-be1c-11ea-9df9-28d7960ad7f1.png)

As you can see, appindicator has taken precedence over Topicon, why not, that's not the issue.

As you can see there are more icons (cloudstation tools)

BUT in comparison : side padding is way too big, and icons are too small.

I tried to force icon sizes in the extension code but did not find how. The best I managed was to increase their size... but padding was increased too so the result was worst.

I'm not asking for a whole "size configuration" option, but I could use help to find the right place to force height / width / padding size.

Thank you !

**Comment by squalou** [comment]
interestingly, for some weird reasons i ended up uninstalling gnome2 related things.

Not sure my pc will boot again ... but in between topicon does the job.. all alone with correct size.

wish me luck on reboot

**Comment by 3v1n0** [comment]
Close as per Fixed by #219
