### ISSUE TITLE
Extension install error

### ISSUE THREAD

**Issue by nebrelbug** [ubuntu/gnome-shell-extension-appindicator#247]
When trying to install this extension (from extensions.gnome.org) I get an error. I've tried restarting the GNOME shell, rebooting my system, etc... no luck.

![appindicator-support-bug](https://user-images.githubusercontent.com/25597854/87327308-267b5200-c4f1-11ea-8a5d-0d5b6327a24a.png)

The extension worked until very recently (I believe it broke yesterday, when I tried to update it?)

I'm on Pop!_OS 20.04.

Here's what I find when I look at the `journalctl` error:

```
JS ERROR: Extension appindicatorsupport@rgcjonas.gmail.com: Gio.IOErrorEnum: An object is already exported for the interface org.kde.StatusNotifierWatcher at /StatusNotifierWatcher
AppIndicators_StatusNotifierWatcher@/home/nebrelbug/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:52:24
maybe_enable_after_name_available@/home/nebrelbug/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/extension.js:51:33
enable@/home/nebrelbug/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/extension.js:56:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

**Comment by prigal** [comment]
Same problem here.

**Comment by Tiger862000** [comment]
Same here

ALT+F2 and `lg` gives me:
`An object is already exported for the interface org.kde.StatusNotifierWatcher at /StatusNotifierWatcher...`

As correctly referenced the issues are similar, yet the suggested fix didn't do the trick :unamused: 

> 
    Go to ~/.local/share/gnome-shell/extensions/ and delete printers@linux-man folder.
    Reset Gnome shell (ALT+F2 r).
    Reinstall extension.


#https://github.com/linux-man/gnome-shell-extension-printers/issues/16#issuecomment-659386580

**Comment by shannonlucas** [comment]
In Pop!_OS 20.04, `gnome-shell-extension-appindicator` is installed by default.  On a fresh install, I see it listed in GNOME Extensions as `Ubuntu appindicators` For the extensions and apps I've installed so far, I see their appindicators.

The System76 support article about it is linked below. It mentions 20.04 at the end of the first paragraph.
https://support.system76.com/articles/status-icons/
