### ISSUE TITLE
VeraCrypt tray icon won't display

### ISSUE THREAD

**Issue by felipe19930** [ubuntu/gnome-shell-extension-appindicator#251]
Hi,

VeraCrypt adds a tray icon after you launch the application, but for some reason this extension is unable to display it.

However, if I use this one instead, it works:

https://extensions.gnome.org/extension/1503/tray-icons/

Thanks.

**Comment by 3v1n0** [comment]
So, I've tested the version compiled for ubuntu focal, but that version (at least) doesn't provide any support for [StatusNotification Icons](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/), so not much that we can do.

If they only support the legacy tray X system, then it won't ever display.

**Comment by felipe19930** [comment]
Oh, that's a bummer.

VeraCrypt uses wxWidgets' [wxTaskBarIcon](https://docs.wxwidgets.org/trunk/classwx_task_bar_icon.html), which follows the [System Tray Protocol Specification](https://freedesktop.org/wiki/Specifications/systemtray-spec) instead. 

If there's currently no intention to support that spec, feel free to close this one.

Thanks.

**Comment by jzazo** [comment]
The version from this [ppa](https://launchpad.net/~unit193/+archive/ubuntu/encryption) does display a proper icon in focal for me.

**Comment by felipe19930** [comment]
@jzazo It does work indeed, but the packager manually patched VeraCrypt to support AppIndicator (download the `*.debian.tar.xz` and check the `001-indicator-support.patch` file inside `/debian/patches/`).

I wonder if the author has interest in getting that patch upstreamed, though...

**Comment by 3v1n0** [comment]
Closed with 96712194a33397015858585404d0eb8c69195613
