### ISSUE TITLE
Icon color in panel

### ISSUE THREAD

**Issue by drakkar1969** [ubuntu/gnome-shell-extension-appindicator#253]
I was wondering why indicator icons do not pick up the default panel icon color. For example, in GNOME shell 3.38 (Arc theme, Papirus icons):

![screenshot-appindicator](https://user-images.githubusercontent.com/18715287/95681530-98426500-0be0-11eb-9412-d41db92b0644.png)

The Deluge appindicator (second from left), uses the default Papirus color (#dfdfdf), while other extension icons use the default color from the Arc theme (#ffffff). 

Are there specific CSS selectors that can be used to define the appindicator icon color?

Many thanks in advance, and thank you for this great extension!

**Comment by vincentmathis** [comment]
I have a similar problem, many appindicator icons use a light color despite if the shell theme is dark or light. Meaning on a light shell theme they are not visible.

![Appindicator icons](https://user-images.githubusercontent.com/33002126/96957942-8cfa0e00-14eb-11eb-9260-8b7ee17e090d.png)

**Comment by tuberry** [comment]
Symbolic icons (`-symbolic.svg`) with proper style class (`system-status-icon`) will respect font size/color. So it seems that non-symbolic icons have been used there.

**Comment by vincentmathis** [comment]
So this working correctly but just not correctly implemented by the specific applications. Good to know.

**Comment by drakkar1969** [comment]
Thanks for the responses, pretty clear this is an issue with application icons
