### ISSUE TITLE
JS ERROR: Exception in callback for signal

### ISSUE THREAD

**Issue by morgantex** [ubuntu/gnome-shell-extension-appindicator#256]
`JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null`

`_createIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:406:26`

`_cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:368:14`

`_updateIconByType@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:574:18`

`_updateIcon@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:601:14`

`_emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47`

`_onPropertiesChanged/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:220:22`

`_onPropertiesChanged@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:214:15`

`refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:51:19`

**Comment by 3v1n0** [comment]
This should be now handled, let me know if it's not the case.
