### ISSUE TITLE
Some Electron-based applications do not show up with version 34

### ISSUE THREAD

**Issue by amato-gianluca** [ubuntu/gnome-shell-extension-appindicator#257]
Hi,
I recently upgraded to Gnome 3.38 and version 34 of this extension. Now, some icons that used to appear in the previous version of the extension do not show up any more. In particular, this is the case for Microsoft Teams and Skype (which I think are both Electron-based application).

**Comment by rouisibra** [comment]
add this to you `/etc/environment` 
```
XDG_CURRENT_DESKTOP=Unity
```

then reboot to apply changes

**Comment by amato-gianluca** [comment]
Does not seem to work.

I added the line to ``/etc/environment``, but the environment variable ``XDG_CURRENT_DESKTOP`` is probably rewritten by GDM, since within the graphical session its value is still ``GNOME`` (while the value is ``Unity`` within a non-graphical virtual terminal).

I also tried by changing the environment variable ```XDG_CURRENT_DESKTOP``` to ``Unity`` specifically for the programs which give problem (I tried both Skype 8.66.0.74 and Teams 1.3.00.25560) without any  result.

**Comment by amato-gianluca** [comment]
I found the culprit. Both Teams and Skype (and probably all Electron based applications) need libappindicator3, which is not installed by default in Fedora 33 and is not required by the above mentioned packages. It might be a good idea to add in the Known Issue section of the README the information that some distributions might require manually installing the appropriate libappindicator library.

**Comment by jatin-cbs** [comment]
yes just install   

`sudo dnf install libappindicator-gtk3`   on fedora 33 that should fix it :+1:   Tested - Discord, Skype

**Comment by Gaw18** [comment]
> yes just install
> 
> `sudo dnf install libappindicator-gtk3` on fedora 33 that should fix it +1 Tested - Discord, Skype

Work also for me that use Debian 10, thank you so much
