### ISSUE TITLE
Memory leaks because of the usage of GdkPixbuf

### ISSUE THREAD

**Issue by lestcape** [ubuntu/gnome-shell-extension-appindicator#259]
This is not properly a bug of this extension, but a [gjs one](https://gitlab.gnome.org/GNOME/gjs/-/issues/52). How this extension need to create a lot of Pixbuf objects the problem occurs, for example in:
- https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/v34/dbusMenu.js#L649
- https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/v34/appIndicator.js#L579

I think this is probably a know issue here, but it should be reported for tracking the gjs issue and alert the users about the problem.

I really don' t see a way to workaround the problem here. The only fix I see is address it in gjs, but how at less one maintainer of the extension is helping in gjs maybe he can also help to fix his own extension from there.

**Comment by 3v1n0** [comment]
Looks like gjs fix may still depend on some GObject stuff that isn't probably coming shortly, so not much to do.... :-(

**Comment by lestcape** [comment]
Yes, a really fix for this it's going to take a lot. I'm waiting for a solution of [this issue](https://gitlab.gnome.org/GNOME/gjs/-/issues/109) that i opened in gjs 3 years ago. So, i know...

Maybe a workaround could be inject a new function `dispose` in the gjs code, to be added to GdkPixbuf and release the memory form there. Something similar to what Cairo.Context use to calling $dispose(). Is an undesirable workaround, but i think a memory leak is worse from the perspective of the ubuntu distro an the extension. Well yes, maybe for gjs a workaround is worse, i don' t know.

**Comment by 3v1n0** [comment]
Sooo.... There's no access to that, but we can mimic it by just calling `GObject.Object.prototype.run_dispose` on the object maybe...

**Comment by lestcape** [comment]
In my opinion if you call `GObject.Object.prototype.run_dispose` this will trigger the dispose of GObject and GObject is thinking there are only a reference there. So, it will dispose just the object proxy's size and the pixbufs content will really never GC.

**Comment by 3v1n0** [comment]
Well this would have worked if gdk pixbuf did the cleanup on `dispose`, but it seems that [this happens only on `finalize`](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/blob/master/gdk-pixbuf/gdk-pixbuf.c#L359), so really there's no much to do.

We can probably change GdkPixbuf to perform this to happen during disposition, I guess there are no troubles with that.

**Comment by 3v1n0** [comment]
In a second though, since gjs is monitoring the object that created disposing it will make it consider a dead object and may still make it release its reference, so it could still work.

Can you maybe try if doing this will work for you?

```diff
diff --git a/appIndicator.js b/appIndicator.js
index d606b8f..a9ff140 100644
--- a/appIndicator.js
+++ b/appIndicator.js
@@ -409,6 +409,8 @@ class AppIndicatorsIconActor extends St.Icon {
         this.connect('destroy', () => {
             this._iconCache.destroy();
             this._cancellable.cancel();
+            if (this.gicon && this.gicon.gicon)
+                this.gicon.gicon.run_dispose();
         });
     }
 
@@ -652,6 +654,9 @@ class AppIndicatorsIconActor extends St.Icon {
     // So when it's not need anymore we make sure to check the .inUse property
     // and set it to false so that it can be picked up by the garbage collector.
     _setGicon(iconType, gicon) {
+        if (this.gicon && this.gicon.gicon)
+            this.gicon.gicon.run_dispose();
+
         if (iconType !== SNIconType.OVERLAY) {
             if (gicon) {
                 this.gicon = new Gio.EmblemedIcon({ gicon });
```

**Comment by lestcape** [comment]
I don't think that dispose also the gicon internal will be ok and also i think you are breaking the icon cache with this change. Run a dispose by hands it's troublesome on its own, but at same, messing with internal implementation of gicon can give us headaches.

Anyway i think this will not work without your first proposition of move the cleanup to the dispose. It need to be tested, if i have a time i will do it, thanks.

**Comment by 3v1n0** [comment]
Indeed, but that's a workaround worth trying.

Disposing is managed by gjs so could have benefits, but indeed not a
clean solution

**Comment by lestcape** [comment]
As my previous comment suggested that this will not work and as we can see in: https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/14805b78b774b9f586cb69526e6eb335b0c6eb2c.

Any other idea then?

**Comment by 3v1n0** [comment]
> As my previous comment suggested that this will not work and as we can see in: [14805b7](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/14805b78b774b9f586cb69526e6eb335b0c6eb2c).
> 
> Any other idea then?

Actually it will work properly once https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/593 will merge as will make the object to be disposed and its property set as undefined.

The reason I removed that (temporary) was to mute the crash with current upstream code, but I plan to set something similar back with relevant null (actually undefined) checks.

**Comment by lestcape** [comment]
Maybe your pull in gjs also will fix this: https://gitlab.gnome.org/GNOME/gjs/-/issues/327 as seem that probably the cause is also part of your target.

**Comment by 3v1n0** [comment]
I've checked but unfortunately it's not the case, I need to see if I can figure it out a bit more

**Comment by pabs3** [comment]
Are there any news about this issue? I'm using gjs 1.70.1-1 and gnome-shell-extension-appindicator from 42-1 Debian bookworm and I still get GNOME shell OOMs, I think they are because of this extension and this issue.

**Comment by 3v1n0** [comment]
I've done some debugging on this, but it seems that even without forcing any disposal gjs handles the pixbufs pretty well right now, and we get them finalized as expected.

I feel the problem is not due to the pixbufs but instead to the St texture cache: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/321#issuecomment-1017810034

**Comment by 3v1n0** [comment]
I think this can be closed, as pixbuf doesn't seem the guilty here.
