### ISSUE TITLE
nextcloud systray icon gone - seems to be a timing issue

### ISSUE THREAD

**Issue by mbogner** [ubuntu/gnome-shell-extension-appindicator#263]
From gnome-shell I was referred to https://gitlab.gnome.org/Community/Ubuntu/gnome-shell-extension-appindicator. But that looks quite dead. My desktop sent me to this project. So not sure which one to use and on the gitlab project there is nothing stated that it has been moved.

So please just check https://gitlab.gnome.org/Community/Ubuntu/gnome-shell-extension-appindicator/-/issues/121 for the bugreport instead of making me copy&paste it a 3rd time.

**Comment by cnmicha** [comment]
Duplicate with #250. And there is already a pull request fixing the bug: #260
