### ISSUE TITLE
how to change flameshot tray icon monochrome on ubuntu 20.04 with gnome-shell

### ISSUE THREAD

**Issue by MrAnon-dev** [ubuntu/gnome-shell-extension-appindicator#266]
Hi,

I managed to change the icon to a custom one using Dash to panel gnome-shell extension (/usr/share/icons/Yaru/24x24/panel/flameshot-tray.png) but no with default installation.

where should the icon be placed for ubuntu 20.04, gnome-shell-extension-appindicator and ubuntu dock (dash-to-dock)¿?

desaturating or converting the original icon to B&W would also be a solution

I have already asked in the flameshot repository (https://github.com/flameshot-org/flameshot/issues/1201)

I´m using flameshot-0.8.5-1.ubuntu-20.04.amd64.deb package

![screenshot](https://i.imgur.com/5kKfA5L.png)

thanks!!

**Comment by terencode** [comment]
You can give #196 a try for the desaturation setting.

**Comment by andrei-a-papou** [comment]
I'm using Flameshot v0.10.1, from a native Debian package on Ubuntu 20.04 and have the same issue. Had to recompile Flameshot and put a custom _fallback_ icon to work around this issue and make it look OK in the top bar.

The `flameshot-tray` icon is not being found for some reason, and the same seems true for _any_ icon from an existing theme. I replaced the call to to `flameshot-tray` with a guaranteed icon name, recompiled, and the fallback icon is still used no matter what.

I'm not 100% positive, but this seems like the  `gnome-shell-extension-appindicator` issue. I can't test now, but I definitely didn't have this problem with XFCE before.

**Comment by andrei-a-papou** [comment]
> You can give #196 a try for the desaturation setting.

This is a useful setting, but I would argue it makes things worse with Flameshot, the icon becomes barely intelligible...

**Comment by 3v1n0** [comment]
Icons can be replaced now, use preferences.
