### ISSUE TITLE
Improve indicator margins

### ISSUE THREAD

**Issue by SaucySauce** [ubuntu/gnome-shell-extension-appindicator#267]
![Screenshot_2021-02-15 Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/38703177/108575597-52be4300-730a-11eb-831a-7fa948e85851.png)

I'm using a custom theme but it's more easily shown here than on the single highlight used by default adwaita. These are all single icon indicators yet have different margins than other extension indicators.
Telegram indicator (top) is provided by the extension.
Pamac (bottom) provided indicator.

**Comment by SaucySauce** [comment]
![Screenshot-20210220003359-70x66](https://user-images.githubusercontent.com/38703177/108578827-99646b00-7313-11eb-901f-401ecb52193d.png)
![Screenshot-20210220003428-69x53](https://user-images.githubusercontent.com/38703177/108578828-9a959800-7313-11eb-9688-d4c33a0f2fa1.png)
This is the result of the pull request. I'm using [AdwMod-theme](https://gitlab.com/hrdwrrsk/AdwMod-theme) but the results are the same on default Adwaita.

**Comment by 3v1n0** [comment]
As explained in https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/268#issuecomment-798899076 this should be done per theme.
