### ISSUE TITLE
error updating the extension

### ISSUE THREAD

**Issue by rafadesign** [ubuntu/gnome-shell-extension-appindicator#271]
when I went to upgrade to the latest version it gave this error

system: fedora 33 workstation
Gnome 3.38.4

![image](https://user-images.githubusercontent.com/46974593/111481413-b40ee180-8711-11eb-884e-e57f7589212b.png)

**Comment by BriggsyUK1970** [comment]
Same issue, same environment today...

system: fedora 33 workstation
Gnome 3.38.4
https://extensions.gnome.org/extension/615/appindicator-support/
file:///home/briggsy_uk/Pictures/Screenshot%20from%202021-03-17%2015-39-11.png

**Comment by rafadesign** [comment]
> Same issue, same environment today...
> 
> system: fedora 33 workstation
> Gnome 3.38.4
> https://extensions.gnome.org/extension/615/appindicator-support/
> ![Screenshot from 2021-03-17 15-39-11](https://user-images.githubusercontent.com/38052156/111495369-365dcc80-8737-11eb-870c-143827db64c0.png)

I managed to solve it, installed the updates on the system

**Comment by BriggsyUK1970** [comment]
Yep, I ran a standard update on packages, rebooted and it's now fine
