### ISSUE TITLE
Shell crash with Microsoft Teams

### ISSUE THREAD

**Issue by ghostshell666** [ubuntu/gnome-shell-extension-appindicator#272]
Teams displays an indicator when running. Whenever I open Teams and log in with this extension running, after a few seconds the shell crashes and I lose the session entirely. Disabling the extension and opening Teams works fine.

Fedora 34 beta, GNOME Shell 40 (final version). Latest stable or latest git, I can reproduce it in both.

A few more details:
* Teams changes the indicator to reflect your online status, that's when the shell crashes. You can do this by changing your status in Teams
* Starting an X11 session instead allowed me to get a glimpse of the crash, seems like a shell/gjs bug
* Fastest way to trigger the crash is to switch from Invisible to Available and vice-versa

**Comment by 3v1n0** [comment]
Mhmh, Do you have any backtrace or coedup of this?

Could be this related to https://gitlab.gnome.org/GNOME/gjs/-/issues/387 ?

**Comment by ghostshell666** [comment]
Tried to reproduce that unlocking crash but no lock, so probably unrelated.

There's a core backtrace auto-generated by ABRT. Seems to always crash in the same function.

[core_backtrace.log](https://github.com/ubuntu/gnome-shell-extension-appindicator/files/6191830/core_backtrace.log)

**Comment by 3v1n0** [comment]
Ok, I'd need the JS backtrace then...

Please provide one as explained in https://is.gd/wiki_gnome_shell_crash_debug

**Comment by ghostshell666** [comment]
Oh cool, that's what I was looking for and couldn't find it. Anyway, took a few tries, see if it's useful.

[gdb.txt](https://github.com/ubuntu/gnome-shell-extension-appindicator/files/6191896/gdb.txt)

[journalctl.log](https://github.com/ubuntu/gnome-shell-extension-appindicator/files/6191897/journalctl.log)

**Comment by 3v1n0** [comment]
Thanks!

Can you please also install the gnome-shell and gjs debug symbols? So I can see if they're doing something weird...
As even if there's a JS error (don't know yet!) shouldn't really crash the shell.

**Comment by 3v1n0** [comment]
Ok, no worries got it... So yeah definitely a gjs issue.
Will close this and handle it upstream.

**Comment by 3v1n0** [comment]
FYI reported as https://gitlab.gnome.org/GNOME/gjs/-/issues/395, I've couple of fixes so if you can please follow the bug and I'll link the MR you can try

**Comment by ghostshell666** [comment]
Thanks, will do.
