### ISSUE TITLE
gnome-shell RAM usage doubles when launching certain applications

### ISSUE THREAD

**Issue by Kneemund** [ubuntu/gnome-shell-extension-appindicator#277]
Launching apps like Discord increases the RAM usage of `gnome-shell` from about 320MB to 670MB. The RAM usage stays at 320MB without this extension.

All versions of this extension I've tried so far (master, latest release, last release) seem to be affected. It happens on GNOME 38 as well as on GNOME 40.

**Comment by guihkx** [comment]
Does that RAM increase happen as soon as you launch Discord? Or does it increase over time?

**Comment by Kneemund** [comment]
I'm pretty sure that it happened as soon as I launched Discord and did not change over time. I can't fully confirm this though as I'm not using GNOME anymore (but I could test it again if that would help).

**Comment by arshetamine** [comment]
There is memory leak when you talk on discord, the app indicator icon changes and causes memory leak.

**Comment by 3v1n0** [comment]
Not sure if this is fully related (could be also due to GdkPixmap's around) but for sure a memory waste is due to cancellables:

https://www.pastery.net/bvfscd/

**Comment by 3v1n0** [comment]
See if commit 75456f8 helps with this specific case.

**Comment by arshetamine** [comment]
> See if commit 75456f8 helps with this specific case.

No 😔, stopped using discord 🤣

**Comment by 3v1n0** [comment]
Let's close this, feel free to reopen in case.
