### ISSUE TITLE
Icons not showing without Xwayland running

### ISSUE THREAD

**Issue by daenney** [ubuntu/gnome-shell-extension-appindicator#279]
I can't believe I'm actually writing this issue, because it feels impossible. But since a recent change in Gnome I no longer get application indicators  in the top bar if the only thing running are native Wayland applications.

My system has an autostart for arch-audit-gtk and firewall-applet (firewalld), but when I log in none of the icons are showing, even though their processes show in `ps`. etc. However, launching an app that causes Gnome to launch Xwayland seems to jigger something and the icons now appear. The Xwayland application I'm launching itself doesn't have to have an application indicator either (for example I'm launching Spotify to trigger it which doesn't have a tray icon, but Discord does and works just as well).

**Comment by Bohne13** [comment]
have the same problem.
Login with Xorg, the app-icons shown in the appindicator bar.
Unter Wayland, they're gone!

**Comment by daenney** [comment]
> But since a recent change in Gnome I no longer get application indicators in the top bar if the only thing running are native Wayland applications.

I just realised this is b/c Gnome 40 defaults to launching XWayland on demand. With the release of Electron 12 I've swapped all my apps to use the wayland ozone backend, so at startup I have nothing that needs X11. This results in nothing triggering the launch of XWayland, which seems to result in no app indicator icons.

**Comment by 3v1n0** [comment]
Thanks for the report, meanwhile I analyze this, is the extension logging anything in the journal?

**Comment by daenney** [comment]
There was nothing that jumped out to me in my journal logs. Do you have anything in particular I could look/grep for?

**Comment by 3v1n0** [comment]
> There was nothing that jumped out to me in my journal logs. Do you have anything in particular I could look/grep for?

`journalctl /usr/bin/gnome-shell|grep appindicatorsupport ` should be enough normally.

**Comment by daenney** [comment]
I'm afraid I don't have anything matching appindicator in the journal for my current boot.

**Comment by 3v1n0** [comment]
Ok, this is due to the fact we're waiting for a never-arriving theme, this is the issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/960

**Comment by daenney** [comment]
Congrats on finding that! That issue was closed as a dupe of another, which has equally been in radio silence mode for a year. That's too bad.

**Comment by 3v1n0** [comment]
Yeah, but still I've figured it out, I will push a fixup in a moment.
