### ISSUE TITLE
Outdated on Fedora 34 (Wayland GNOME 40)

### ISSUE THREAD

**Issue by janvlug** [ubuntu/gnome-shell-extension-appindicator#281]
The GNOME extensions website states that this extension is outdated:

![image](https://user-images.githubusercontent.com/5903208/116779881-3e6c9400-aa79-11eb-9794-95384259d1f4.png)

I am using Fedora 34, with GNOME on Wayland.

**Comment by KopfKrieg** [comment]
@janvlug You're looking at the wrong extension. Use this link instead: https://extensions.gnome.org/extension/615/appindicator-support/

Issue can be closed.

**Comment by janvlug** [comment]
I'm confused. I have [Top Indicator App](https://extensions.gnome.org/extension/3681/top-indicator-app/) installed that has this repository as homepage.
Is Top Indicator App deprecated, or an unsupported fork?

**Comment by 3v1n0** [comment]
Mh, I think that's a duplicated entry, should probably be disabled if there are no changes

> This extension is 'appindicators' from ubuntu, renamed 'top indicator app' under the terms of the GPL v2 +. it is the extension itself that Ubuntu offers as a native experience on your system, but so you can install it in other distros since the current one in gnome-extensions is empty.I will offer stable updates when possible.
