### ISSUE TITLE
Firefox and Thunderbird indicators?

### ISSUE THREAD

**Issue by phokas** [ubuntu/gnome-shell-extension-appindicator#282]
This is probably more of a question than a workable issue.

Some background: When I tried Ubuntu 17.10 a few years ago (out of curiosity, to follow the transition to GNOME Shell), the following things worked out-of-the-box:

a) Firefox showed a little red indicator when downloading files
b) Thunderbird showed a little red indicator for unread mail

I have recently installed Ubuntu 20.04 LTS and no matter I try, the indicators are not there and I'm not able to get them back on. They don't seem to be there in Ubuntu 21.04 either (or Fedora 34 with this extension).

So, the question is:

Is this a regression in the AppIndicator extension that has happened over the years (assuming this is the correct place to ask), or has it something to do with the Mozilla applications? I would appreciate some clarification, as it is baffling to not have this basic functionality working on a desktop (coming from KDE software, I might add).

**Comment by 3v1n0** [comment]
Those applications were patched in ubuntu to include indicators, but this is not the case anymore so nothing will show up sadly.
