### ISSUE TITLE
No icons from Wine System Tray

### ISSUE THREAD

**Issue by IvoryJam** [ubuntu/gnome-shell-extension-appindicator#284]
I'd love to see icons from Wine System Tray, ones generated from Lutris, specifically Epic Games.
There are other extensions that do this, but I'd love it if the best one could do it too!

**Comment by jatin-cbs** [comment]
Same all other extension like Tray icons, Tray icons reloaded do have wine system tray support. But still I prefer this one as it works in overview where as others don't. Please bring wine system tray support.

**Comment by 3v1n0** [comment]
Fixed by #96712194a33397015858585404d0eb8c69195613
