### ISSUE TITLE
Tray icons not displaying after update to latest git version

### ISSUE THREAD

**Issue by drakkar1969** [ubuntu/gnome-shell-extension-appindicator#285]
Running on GNOME Shell 40.1

Output of `journalctl /usr/bin/gnome-shell|grep appindicatorsupport`:
[appindicator.txt](https://github.com/ubuntu/gnome-shell-extension-appindicator/files/6610489/appindicator.txt)

Thanks for the awesome extension, btw, one of my must-haves

**Comment by 3v1n0** [comment]
You need to compile the settings schema file now: `make compile-schema` will do it for local installations, otherwise need to add it to your datadir, [see this](https://gnome-shell-extension-examples.readthedocs.io/en/latest/gsettings1.html).

**Comment by drakkar1969** [comment]
Thanks for responding so quickly. Looks like this is an AUR packaging issue, where the settings schema file is not compiled (actually not even present)
