### ISSUE TITLE
Doesn't work after v39 update

### ISSUE THREAD

**Issue by guihkx** [ubuntu/gnome-shell-extension-appindicator#286]
I've tried uninstalling v38, rebooting and then installing v39 from the Extensions website, but I'm still getting this error:

```js
Jun 07 22:53:25 arch gnome-shell[744]: JS ERROR: GLib.FileError: Failed to open file “/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory
                                       getSettings@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/convenience.js:83:31
                                       SettingsManager@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/settingsManager.js:40:39
                                       getDefault@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/settingsManager.js:27:31
                                       getDefaultGSettings@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/settingsManager.js:49:28
                                       _init@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:412:42
                                       _init@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:156:13
                                       _registerItem@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:103:32
                                       async*_ensureItemRegistered@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:128:14
                                       RegisterStatusNotifierItemAsync@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:186:14
                                       async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                       _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34
Jun 07 22:53:26 arch gnome-shell[744]: JS ERROR: Exception in callback for signal: icon: GLib.FileError: Failed to open file “/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory
                                       getSettings@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/convenience.js:83:31
                                       SettingsManager@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/settingsManager.js:40:39
                                       getDefault@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/settingsManager.js:27:31
                                       getDefaultGSettings@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/settingsManager.js:49:28
                                       _updateIconSize@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:784:42
                                       _updateIcon@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:754:14
                                       _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                       _onPropertiesChanged/<@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:341:41
                                       _onPropertiesChanged@/home/gui/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:341:23
```

* OS: Arch Linux
* GNOME Shell 40.1.0

**Comment by guihkx** [comment]
The [manual installation steps](https://github.com/ubuntu/gnome-shell-extension-appindicator#installation) described in the README still work, though. 👌

**Comment by Apfel** [comment]
Running the following command fixes this problem too, perhaps someone forgot to compile the schema.
```sh
glib-compile-schemas ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas
```

**Comment by bkhl** [comment]
> Running the following command fixes this problem too, perhaps someone forgot to compile the schema.
> 
> ```shell
> glib-compile-schemas ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas
> ```

That fixed it for me, and after this change it appears the plugin works _even better_. Previously I didn't get the Hexchat tray icon, but that started working now.

**Comment by PranavBhattarai** [comment]
In Fedora 34, the extension updated successfully but it throws this error message.

```
GLib.FileError: Failed to open file “/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  getSettings@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/convenience.js:83:31
  _init@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:27:38
  buildPrefsWidget@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:143:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
What does this means?!

**Comment by sjustintaylor** [comment]
> In Fedora 34, the extension updated successfully but it throws this error message.
> 
> ```
> GLib.FileError: Failed to open file “/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory
> 
> Stack trace:
>   getSettings@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/convenience.js:83:31
>   _init@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:27:38
>   buildPrefsWidget@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:143:18
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```
> 
> What does this means?!

> In Fedora 34, the extension updated successfully but it throws this error message.
> 
> ```
> GLib.FileError: Failed to open file “/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory
> 
> Stack trace:
>   getSettings@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/convenience.js:83:31
>   _init@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:27:38
>   buildPrefsWidget@/home/pranav/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:143:18
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```
> 
> What does this means?!

If you open a terminal and run 
```
glib-compile-schemas ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas
```
and then toggle the extension on and off, the problem will resolve itself. It's just missing the schema.

**Comment by Ceralor** [comment]
Took me a bit to figure out that solution. This should be compiled ahead of time or being compiled at install time for the release.

**Comment by b-reich** [comment]
gnome auto update this extension
looking for this issue/fix is not the best user experience

**Comment by nos1609** [comment]
looks like fixed for me on F34 with recent update, needed to reboot and re-enable extensions btw

**Comment by 3v1n0** [comment]
The schema file is something that gnome-shell should do, as it's endianness dependent so I suppose I can't just ship it with the extension zip file.

You can compile it easily or follow the default installation guideline.

**Comment by Apfel** [comment]
> The schema file is something that gnome-shell should do, as it's endianness dependent so I suppose I can't just ship it with the extension zip file.
> 
> You can compile it easily or follow the default installation guideline.

Wouldn't compiling the schema automatically inside the extension (assuming that's possible) fix the problem?

**Comment by mbidewell** [comment]
When I install from the extensions website, the schemas directory doesn't exist.  Am I the only one seeing that?

**Comment by 3v1n0** [comment]
Sorry I took a bit more to close this even if trivial to fix because I wanted to ensure that the shell will handle the case properly in future (via https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1875).

Next update (v40) should work without any manual step.

**Comment by guihkx** [comment]
No worries, thanks for you hard work :)

**Comment by PranavBhattarai** [comment]
Any ETA or milestone! @3v1n0

**Comment by 3v1n0** [comment]
@PranavBhattarai I've already uploaded the new version to e.u.o, so it should be approved soon.
