### ISSUE TITLE
JS ERROR when switching workspace

### ISSUE THREAD

**Issue by terencode** [ubuntu/gnome-shell-extension-appindicator#291]
I get the following logged each time I switch to a different workspace : 

```
JS ERROR: Error: Expected an object of type ClutterActor for argument 'sibling' but got type undefined
                                                       _syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:18
```

I'm using the latest extension code (up to 4463b844af7c56ba9b618fb16866e871f2bdde5c) and I'm on GNOME 40.3. 

When I disable the extension, the error goes away.

**Comment by 3v1n0** [comment]
Mh, I'm getting this also with the extension disabled, so i doubt it's related to it.
