### ISSUE TITLE
wayland touchscreen

### ISSUE THREAD

**Issue by dexterdy** [ubuntu/gnome-shell-extension-appindicator#303]
hello there,

I am making this issue, because i cannot click icons using touchscreen on wayland.

GNOME: 40.3.0
Distro: Fedora
Version: latest from gnome extension site
Icons i've tested: microsoft teams, discord

Steps to reproduce:
Open a new wayland session. Open any program with a tray icon. Try to click the icon using your touch screen. I can see the grey bubble that shows when you hover over such an icon with your mouse normally, but nothing happens on release. 

I know touch events are handled separately from mouse events on wayland, so i am guessing that is what's causing it. If you're fixing it, don't forget to implement long-press for right-click while you're at it.

**Comment by 3v1n0** [comment]
From my tests this is true only for legacy tray icons, as I guess you're using there (as per missing libappindicator I suppose).
