### ISSUE TITLE
Gnome 41 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [ubuntu/gnome-shell-extension-appindicator#307]
Greetings,

Gnome 41 was released this month and I was wondering if/when the extension will be updated? Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

**Comment by frandieguez** [comment]
I have tested your extension by simply adding the new version to the scroll-workspaces/metadata.json file.
```
    "shell-version": [
...
        "40",
        "41"
    ],
```

It will be awesome to have your extension compatible on day-one.
