### ISSUE TITLE
Left mouse click for native appindicator icons works as right click

### ISSUE THREAD

**Issue by jwrdegoede** [ubuntu/gnome-shell-extension-appindicator#313]
This was originally reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=2017313

"Mouse Left button do the same as mouse right button, previous for some applications for example skype and nagstamon when click with the left mouse button these applications were showing windows for example."

I've reproduced this with Solaar, where a left click is supposed to show the Solaar window, but instead it shows the same options menu as a right-click does.

Left click vs right click does work normally for me with the hexchat icon, which is a legacy X11 trayicon.

Note this is on Fedora 34 (GNOME40) with gnome-shell-extension-appindicator-41.

**Comment by dinhokusanagi** [comment]
This is redundant, the right mouse button should open the menu and the left button should allow you to open the application thus avoiding muscle fatigue. When studying logic programming is one of the subjects studied and this logic does not make any sense
