### ISSUE TITLE
Custom icons lead to unwanted overlay icons

### ISSUE THREAD

**Issue by andia89** [ubuntu/gnome-shell-extension-appindicator#314]
An issue when using the newly introduced custom icons #287 is that whenever _invalidateIcon is called also an unwanted overlay icon is created (I wasn't really able to pin it down further where this happens). This leads to the situation  that the same icon is drawn twice, once as the real icon and once as a smaller version of itself in the right corner. This only happens with custom icons (I think because the custom icon function only differentiates between Normal and ATTENTION icon, but not the overlay?)

(Here an example where the custom icon is set to gtk-edit)
![image](https://user-images.githubusercontent.com/6475757/139272336-c2eb3390-857f-413e-847a-f410c5047080.png)

To reproudce set a custom icon and restart the gnome-shell (Alt+F2 - r)

Update: Problem is this line:

https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/ca543e59f939c2d0a7d81634418287f459d08c87/appIndicator.js#L752

if there is no gicon in the first try (which there shouldn't because there is no overlay icon) it will create an overlay icon just from the normal icon, right? I think lines 751-754 should just be removed, shouldn't they?

**Comment by 3v1n0** [comment]
Fixed now by commits cab49d3341e911d3e2eb2162a6b163cb159fe4f8 and 139d253366bb9f0cd9d082b9cacd555bdd11bb27
