### ISSUE TITLE
Inconsistent behaviour on click

### ISSUE THREAD

**Issue by winkelnp** [ubuntu/gnome-shell-extension-appindicator#318]
Sometimes when an icon (like for example nextcloud) is clicked on, it will open a menu that fits to the GNOME shell, showing the options for that icon, but other times, clicking on the icon will open the app, while right clicking will open a menu that looks completely out of place on a GNOME desktop.

Is this intended functionality?

I'm on GNOME 41.1 on Manjaro if that makes a difference

**Comment by vanvugt** [comment]
That's probably intended. Indicator menus can have whatever look the app wants them to have.

I suspect this issue should be closed.
