### ISSUE TITLE
Memory leak with one indicator

### ISSUE THREAD

**Issue by garethhumphriesgkc** [ubuntu/gnome-shell-extension-appindicator#321]
Hi,

Whenever this extension is turned on I get a memory leak in gnome-shell that eventually crashes my box. When the extension is disabled everything is normal.

The only indicator it displays is that for "variety" - https://github.com/varietywalls/variety

What info can I supply to help debug?

Ubuntu 21.10
gnome-shell-extension-appindicator 40-1 (installed via apt)
variety 0.8.5-1 (installed via apt)

**Comment by garethhumphriesgkc** [comment]
Related: https://github.com/varietywalls/variety/issues/477

**Comment by 3v1n0** [comment]
I've the feeling this could be related to https://twitter.com/mild_sunrise/status/1458739604098621443 (read the whole thread)

**Comment by garethhumphriesgkc** [comment]
Hi,

Thanks for the tip.  I've read the thread, and don't think it's related though.  I don't get any weird rendering issues, everything looks fine until I get an OOM.  If I keep an eye on it on top I can see the memory use of gnome-shell go up over time, and that only happens when this extension is enabled.  Interestingly, disabling the extension doesn't recover the memory already lost.

**Comment by pabs3** [comment]
This sounds like it could be the same as #259?

**Comment by garethhumphriesgkc** [comment]
Maybe - how would I prove that one way or another?  Happy to collect more info if it helps.

**Comment by pabs3** [comment]
I have no idea to be honest, GNOME shell debugging stuff is very opaque to me.

**Comment by funkyfourier** [comment]
I have this problem too when running [QJackCtl](https://qjackctl.sourceforge.io/). With the "Enable system tray icon" enabled, after encountering an audio drop out (xrun), the QJackCtl system tray icon blinks with a red background color.

It looks like this, with the red background color fading in and out continously:

![QJackCtl sys tray blinking red](https://i.imgur.com/wEaKXOP.png) 

In this state it leaks memory like crazy. After a few days gnome-shell is up to 6-7 gigabytes. I have noticed that without the QJackCtl icon blinking there is no memory leaking.

This is on Manjaro Gnome with AppIndicator  v41.
