### ISSUE TITLE
Now broken on Gnome 42 main / 42.alpha

### ISSUE THREAD

**Issue by timocapa** [ubuntu/gnome-shell-extension-appindicator#324]
All extensions off, journalctl cleared before this. This worked on a build from like a week ago.

Upon toggling the extension on (and having a program open which uses it), the shell crashes a few times until I get to the Something went wrong / logout screen

Posted the (journalctl) log to pastebin, don't really know how to do proper debugging, sorry.

https://pastebin.com/S7ixV1vP

I don't expect anything to happen quickly, just to track it I suppose?

**Comment by techtino** [comment]
Can confirm this happens for me on gnome 42 alpha also.

**Comment by 3v1n0** [comment]
This has been reported [upstream in GNOME shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4974), it seems more likely a gjs issue so far, I will look into it.

**Comment by timocapa** [comment]
Seems to have been fixed, but gonna wait for @3v1n0 to confirm and close to make sure :)

**Comment by gilvbp** [comment]
Gnome shell still crashing! Waiting for the fix.

**Comment by kubrickfr** [comment]
This is now [fixed upstream](https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/729).

However, there is still an unhandled promise rejection warning:

```
Feb 21 17:31:27 XPS-20 gnome-shell[243357]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                              _checkGC@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/iconCache.js:109:19
                                              add@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/iconCache.js:62:14
                                              _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:489:37
                                              async*_createIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:770:42
                                              _updateIconByType@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:756:32
                                              _updateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:801:14
                                              _invalidateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:825:14
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                              reset@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:353:14
                                              _ensureItemRegistered@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:128:18
                                              RegisterStatusNotifierItemAsync@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWatcher.js:190:14
                                              _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:354:35
                                              _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34

```

**Comment by Whayme** [comment]
This appears to be happening again in GNOME 43, at least as described in #331.  [Here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5911) is the issue as I originally opened in the gnome-shell tracker, and [here](https://retrace.fedoraproject.org/faf/reports/517071/) is the gnome-abrt report.  For me, Doom Eternal consistently triggers the crash.

**Comment by 3v1n0** [comment]
@Whayme can you please try #364  ?

**Comment by Whayme** [comment]
@3v1n0 that does seem to fix it, at least in the case of the id tray icon crash.  

Apologies, but how would I go about uninstalling that to go back to the regular version when the fix reaches there?  I followed the installation directions in this repo.

**Comment by 3v1n0** [comment]
> Apologies, but how would I go about uninstalling that to go back to the regular version when the fix reaches there? I followed the installation directions in this repo.

You should get the update anyways, as the metadata value will be lower, btw fastest way is just to remove `~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com` and install it again.
