### ISSUE TITLE
[Feature request] Option for single click to open/focus on app

### ISSUE THREAD

**Issue by darkblaze69** [ubuntu/gnome-shell-extension-appindicator#325]
Please add and option for single click to open/focus on app.
Now to open an app from tray you should double click on it.

**Comment by 3v1n0** [comment]
Sadly we've not such control on icons and we don't have either a direct connection between it and the app, so we can't easily assume the windows it owns.

See https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84
