### ISSUE TITLE
Blank icons after woke up from suspend

### ISSUE THREAD

**Issue by ibahnasy** [ubuntu/gnome-shell-extension-appindicator#329]
Every time I wake up the laptop from suspend, there is a new blank icon get inserted in the systray as shown in the screenshot
![Screenshot from 2022-02-22 15-13-43](https://user-images.githubusercontent.com/19417705/155141832-27d45952-dd38-44da-90b1-45c5e995979e.png)
.

**Comment by stefanoginella** [comment]
It is happening to me too.

Using Manjaro "Qonos" 21.2.4 with Gnome 41.3 and X11.

**Comment by identithree** [comment]
Same here. Every wake from suspend, I get these ghost icons.
I am running Fedora 35 Workstation with GNOME 41.4 with Wayland

**Comment by captfanta** [comment]
Same for me using Pop!_OS 21.10 with GNOME 40.4 and X11.

**Comment by camlafit** [comment]
it's an #317 duplicate

**Comment by 3v1n0** [comment]
Duplicate of #317
