### ISSUE TITLE
Doesn't work under GNOME 41 anymore

### ISSUE THREAD

**Issue by JamiKettunen** [ubuntu/gnome-shell-extension-appindicator#332]
Attempting to install via [GNOME extensions](https://extensions.gnome.org/extension/615/appindicator-support/) results in an error under Void Linux for example with GNOME 41.

**Comment by filipemelo2002** [comment]
Same problem here.
![image](https://user-images.githubusercontent.com/26236991/155521784-b70e3a5c-68da-4016-9558-3b8be6fde6aa.png)

**Comment by TanZng** [comment]
Same here, the `journalctl -n 10 /usr/bin/gnome-shell` says:

```bash
feb 24 09:16:09 user gnome-shell[4204]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from >
feb 24 09:16:26 user gnome-shell[4204]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from >
feb 24 09:21:41 user gnome-shell[4204]: JS ERROR: Extension appindicatorsupport@rgcjonas.gmail.com: Error: A different version was loaded previously. >
                                               loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:343:52
                                               callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
                                               gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

**Comment by TanZng** [comment]
> Mhmmh, doesn't seem a problem with the extension per sé as I've been testing it in 41, mostly in the updater though.....
> 
> Restarting the session doesn't help, I suppose, does it?

This worked for me, thank youu

**Comment by zachspar** [comment]
Was working just fine, then I updated the extension, now it is not working.

**System Info**
OS: Fedora Linux 35 (Workstation Edition)
GNOME: 41.3
Windowing: X11

**Comment by JamiKettunen** [comment]
Restarting the session fixed the issue for me as well, I'll close this now :)
