### ISSUE TITLE
root user cannot show the label 

### ISSUE THREAD

**Issue by myenglishmail** [ubuntu/gnome-shell-extension-appindicator#336]
I ->
dowloads the git
meson
ninja install
enable
with root user

then ,ran a tray app(python3 ), the icon can be show, but the label not shown, 
but switch to the normal user, the icon and label can be shown,

why ?

**Comment by myenglishmail** [comment]
ubuntu 20
gnome shell 3.36.2

**Comment by KMouratidis** [comment]
This happens with backintime as well (also running with python). Launching as root doesn't display icons:

![Screenshot from 2022-03-27 11-59-14](https://user-images.githubusercontent.com/26832680/160277659-7847e87f-276e-4f3d-920f-0837f5f378b9.png)

Fedora 35
GNOME Shell 41.4
backintime 1.3.1

**Comment by 3v1n0** [comment]
No way to fix this... Unless the application will make the icon readable by the gnome-shell process.
