### ISSUE TITLE
Double click on the icon tray doesn't open application on Gnome 42

### ISSUE THREAD

**Issue by martinspudich** [ubuntu/gnome-shell-extension-appindicator#345]
Hi,

today I got an upgrade on Manjaro Linux with Gnome 42. After the upgrade, I'm not able to open an application window by double-clicking on the tray icon. It was working on Gnome 41.

It isn't very pleasant in the case of Clementine, Toggle Tracer, or JetBrain Toolbox.

Thank you in advance.

**Comment by AsciiWolf** [comment]
I can also reproduce this issue on Fedora 36 (with gnome-shell-extension-appindicator-42-1.fc36), however only with some apps (for example Telegram).

**Comment by CroMarmot** [comment]
Same Ubuntu 22.04.1(Linux 5.15.0-47-generic) GNOME 42.4

**Comment by barreiroleo** [comment]
Same here. Gnome 42.4 on Arch

**Comment by admorgan** [comment]
Same on openSUSE Tumbleweed.

**Comment by 3v1n0** [comment]
If such applications are using appindicators,then it's not supported.

This is only possible with legacy tray icons. Ensure if that's the case, and if not please re-open the issue.

**Comment by 3v1n0** [comment]
Oh, I think that's actually an issue as click count has been removed: https://gitlab.gnome.org/GNOME/mutter/-/commit/3d37602
