### ISSUE TITLE
Dropbox menu not working

### ISSUE THREAD

**Issue by dnohales** [ubuntu/gnome-shell-extension-appindicator#346]
I hope this can be reproduced, I saw a comment with the same issue in the [GNOME extensions page](https://extensions.gnome.org//extension/615/appindicator-support/). Dropbox menu simply doesn't work, it shows the icon properly, it changes icon status, but clicking/right clicking on it does nothing. Other apps like Slack, Steam and Zoom work ok.

My system is:

- Fedora 36
- GNOME 42.1
- I installed the extension manually using [Extension Manager](https://github.com/mjakeman/extension-manager).

**Comment by AsciiWolf** [comment]
Try installing the `libappindicator-gtk3` package, or better, use a `gnome-shell-extension-appindicator` package from Fedora repository (you will also need `gnome-extensions-app` to enable the extension) instead of the AppIndicator extension version from _extensions.gnome.org_.

**Comment by dnohales** [comment]
Oh! it worked, sorry for the trouble.

**Comment by Arecsu** [comment]
> Sorry to reopen this issue, but I have the same problem with Dropbox since 3 or 4 month in Arch Linux since we arrive to gnome 45 . I followed the instruction here (install the appindication package and gtk3) and it is not solved. Is there any other trick?

for me the dropbox menu (right click on the app indicator in gnome-shell)  stopped working when I installed ` libappindicator-gtk3`. Had to uninstall the package, kill the process and open it again for the menu to work. It is not the beautiful menu some distros have it though, but at least it works. Double click on the icon and it should open.

**Comment by RichardJECooke** [comment]
When trying to fix this problem, ensure you disable all extensions first - like dash to panel, astro, weather.

**Comment by RichardJECooke** [comment]
The dropbox menu doesn't work when the indicator extension is installed and the dash to panel extension is installed.

However, the protondrive system tray icon menu works fine with both extensions installed. So does steam. Only Dropbox has problems.

**Comment by netsurfer38** [comment]
It appears that one needs to have the **AppIndicator and KStatusNotifierItem Support** gnome extension installed for the Dropbox menu to work.

However the menu no longer works after Powering Off or doing a Restart. However other forums state that the menu is restored after locking the screen by pressing "Windows+L" or "Super+L" and then unlocking the screen again. This has worked for me.

It seems that Dropbox does not play well with some gnome extensions such as **Dash to Panel**. However the aforementioned Lock screen trick works with **Dash to Panel** enabled.
