### ISSUE TITLE
Duplicate icon for KeeWeb

### ISSUE THREAD

**Issue by palexdev** [ubuntu/gnome-shell-extension-appindicator#348]
I have this issue where every time I open KeeWeb and then close it (minimizing it to the tray) a new icon is added. Every previous icon doesn't work. Each icon can open the context menu but the action do not work except for the last added icon
Would be great if this could be fixed please
![Screenshot from 2022-06-16 12-15-05](https://user-images.githubusercontent.com/16880178/174048941-119e6886-9d2f-4d34-88cb-04e04e577f3d.png)

System Info:
Distro: Garuda Linux
Shell: 42.2
Extension: latest from extensions.gnome.org
Indicator: KeeWeb
How to reproduce: simply install KeeWeb from pacman (to be precise the package is keeweb-desktop-bin from AUR)

**Comment by Alt37** [comment]
Possibly related issues:
• https://github.com/electron/electron/issues/24976
• https://github.com/ferdium/ferdium-app/issues/57
• https://github.com/martpie/museeks/issues/479

**Comment by palexdev** [comment]
> Possibly related issues: • [electron/electron#24976](https://github.com/electron/electron/issues/24976) • [ferdium/ferdium-app#57](https://github.com/ferdium/ferdium-app/issues/57) • [martpie/museeks#479](https://github.com/martpie/museeks/issues/479)
> 
> I'm facing a bug with Ferdium but can't reproduce it with other extensions ([Tray Icons: Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded) , [Top Icons Fix](https://extensions.gnome.org//extension/1674/topiconsfix/), [Unite](https://github.com/hardpixel/unite-shell) )

I'm now using [Tray Icons: Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded) and I can confirm that the issue is not present

**Comment by 3v1n0** [comment]
The others extensions are not using app-indicators, so it's not comparable.

However, are you using the latest version of this extension?
As I don't see it happening on last one (at least with ferdium, I can't see the appindicator at all in KeeWeb here)

**Comment by 3v1n0** [comment]
Ok, I got a reproducer by following https://github.com/ferdium/ferdium-app/issues/57#issuecomment-1118738221 not sure if that's the same issue though yet.
