### ISSUE TITLE
kDrive appimage (fork of Nextcloud client) doesn't open after reboot

### ISSUE THREAD

**Issue by supertoni3c** [ubuntu/gnome-shell-extension-appindicator#354]
I use kDrive which as far I know is a fork of Nextcloud client. After installation of the extension, the indicator is displayed correctly and after clicking on it the app's window is opening correctly. However after reboot/next log in nothing happens after clicking on the indicator. I suspect that the issue is related to the fact that it's the qt app as e.g., Joplin behaves as expected. 

On the other hand, everything is okay when I use the extension "Tray Icons: Reloaded". 

**Operating system: Fedora 36 Silverblue (Gnome 42)
   Application: kDrive-3.3.5.20220608**

**Comment by supertoni3c** [comment]
I think it's related to this issue: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/345

**Comment by 3v1n0** [comment]
Please check  if this is fixed now, as #345 is closed.

**Comment by supertoni3c** [comment]
Indeed, it works now.
