### ISSUE TITLE
xdg-activation support

### ISSUE THREAD

**Issue by ilya-fedin** [ubuntu/gnome-shell-extension-appindicator#358]
There was a recent addition to the SNI spec to support the xdg-activation Wayland protocol: https://github.com/KDE/knotifications/blob/c40af19e1a733ad20ae2989eca942a89fc99028d/src/org.kde.StatusNotifierItem.xml#L52-L54

I'm currently adding Qt support for this: https://codereview.qt-project.org/c/qt/qtbase/+/428405

If everything goes ok, the support should be in Qt 6.4 that is planned to out at [September 29](https://wiki.qt.io/Qt_6.4_Release). There's a chance though that we in tdesktop switch to 6.4 at its Beta 4 release though (too much improvements :P). We in tdesktop plan to take advantage of this feature, I hope Ubuntu will be ready by that time.

**Comment by 3v1n0** [comment]
Oh, yeah... That's definitely something we missed.

I'll add support for this in the coming weeks.

**Comment by 3v1n0** [comment]
I wanted to do some work related to the activation token in mutter too, though... As it's currently using some non-standard tokens.

**Comment by ilya-fedin** [comment]
You refer to gtk-shell?
