### ISSUE TITLE
Crashes on resume from lock screen in with g-s 43

### ISSUE THREAD

**Issue by Vash63** [ubuntu/gnome-shell-extension-appindicator#365]
Every time I login after locking the screen with either Super+L or the sleep timeout, Gnome-shell crashes in gjs. Disabling this extension fixes it.

**Comment by 3v1n0** [comment]
Can you check if https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/364 fixes it?

**Comment by Vash63** [comment]
Yes, it does.
