### ISSUE TITLE
Latest release version number is misleading

### ISSUE THREAD

**Issue by AsciiWolf** [ubuntu/gnome-shell-extension-appindicator#367]
The gnome-shell-extension-appindicator v44 that got released recently has quite a misleading version number. Previously, the number did correspond with the gnome-shell version. Ideally, the bugfix release of v43 should be v43.1, not v44.

**Comment by 3v1n0** [comment]
I agree with that... And that wanted to be my rule too... 

But, versions in extensions.gnome.org are increasing 1 by one automatically (see https://extensions.gnome.org/extension/615/appindicator-support/) and I want to keep the two in sync to make things easier to track.
