### ISSUE TITLE
JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty:

### ISSUE THREAD

**Issue by tlo8640** [ubuntu/gnome-shell-extension-appindicator#370]
Hello,

first, thank you very much for providing this very helpful extension. I really appreciate your maintaining and developing over the last gnome version. Without this Extension, my user expierience would be much worse.

I'm not sure since when, but I think, with one of the 2 last updates(45 or 46) this extension started to fill system log with the following error message:
```
Sep 30 09:27:52 galadriel gnome-shell[8507]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: Property org.kde.StatusNotifierItem.IconAccessibleDesc was not found in object /StatusNotifierItem
                                             _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:446:45
                                             ### Promise created here: ###
                                             getProxyProperty@/home/smiler/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:55:31
                                             refreshPropertyOnProxy@/home/smiler/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:73:39
                                             _translateNewSignals/<@/home/smiler/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:268:18
                                             _translateNewSignals@/home/smiler/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:267:50
                                             _onProxySignal/<@/home/smiler/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:56
                                             _onProxySignal@/home/smiler/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:294:38
                                             async*AppIndicatorsAppIndicator/<@/home/smiler/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:105:76
```

I'm using Debian Testing, with gnome 42.4
A couple of gnome libraries re already moved to version 43. If you need the version of selected librries for going deeper (if this issue is important enough to do it) I can provide it, but there are to many libraries for the gnome desktop for being sure wich one is needed in this case and post everything here.

Thank you very much and best regards
Thomas

**Comment by 3v1n0** [comment]
Those are just debugging bits, but indeed we can mute them in some cases.

**Comment by tlo8640** [comment]
Hello, 
thank you for your response.
Ah okay, that reduces my panic mode to a normal level.. ;-)
Sure, debugging output is important, for developing or at least debugging ;-)
It also helps when submitting issues. But if everything is working I'd like to not see them ;-)
at least, this message comes very often... 2 times per minute
Perhaps it could be a possibility, to enable/disable debug output somehow in the settings window?
Thank you very much for your work
Thomas

**Comment by lynix** [comment]
I cherry-picked 00f30a1 into my local version and I'm still getting those messages:

```
gnome-shell[1426]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: Property org.kde.StatusNotifierItem.IconAccessibleDesc was not found in object /StatusNotifierItem
                                        _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:446:45
                                        ### Promise created here: ###
                                        getProxyProperty@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:55:31
                                        refreshPropertyOnProxy@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:73:39
                                        _translateNewSignals/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:265:18
                                        _translateNewSignals@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:264:50
                                        _onProxySignal/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:291:56
                                        _onProxySignal@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:291:38
                                        async*AppIndicatorsAppIndicator/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:102:76
```

Is this expected or do I need another commit?

**Comment by MaxXor** [comment]
Will there be a new release with this fix included? It's spamming the logs on Arch Linux with GNOME 43.

**Comment by darkblaze69** [comment]
This is still happening at least with telegram app launched. A lot of spamming in log with this error. Extension v46 on GNOME 43.

**Comment by darkblaze69** [comment]
> 

I have upgraded to github master version, and spamming gone. Thanks

**Comment by julian-alarcon** [comment]
It seems to be happening again
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/445

**Comment by b3** [comment]
Is there a way to stop seeing these messages in logs under Debian 12.2 (Gnome 43.6, Extension v46-1?

**Comment by cweiske** [comment]
@b3 Uninstall the apt package via
```
$ apt purge gnome-shell-extension-appindicator
```
and then install it from the extensions website: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by b3** [comment]
@cweiske Thank's I just tried that.

After a reboot it seems to have stopped the trouble. I'll watch my log to ensure it is permant.
