### ISSUE TITLE
Please create a new release.

### ISSUE THREAD

**Issue by karolyi** [ubuntu/gnome-shell-extension-appindicator#392]
Hey,

v46, as in included in many linux distributions, contains the bug #380, and keeps spamming the system log.

As there is no release ever since, everyone who uses the distribution provided appindicator (like me), will have the problem.

Could you please provide a new release so distributions could update as well?

Thanks.

**Comment by SEARANATAT** [comment]
Yes to this! also waiting for a new release on Fedora that includes the fix for #370 and #380

**Comment by jmastr** [comment]
> v46, as in included in many linux distributions, contains the bug #380, and keeps spamming the system log.

For me this is actually a reason to disable this otherwise perfect extension

**Comment by mvhirsch** [comment]
@3v1n0 please help

**Comment by karolyi** [comment]
bump

**Comment by 3v1n0** [comment]
Done in https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v47 under review at e.g.o: https://extensions.gnome.org/review/38790
