### ISSUE TITLE
Steam Icon is pixelated

### ISSUE THREAD

**Issue by Anicaloid** [ubuntu/gnome-shell-extension-appindicator#403]
Hello! After the new update Steam icon looks like this:
![image](https://user-images.githubusercontent.com/83916391/222437697-a9e82a4b-d1c3-401a-9cc5-39eeac05de50.png)

I think you fixed the Discord icon changing into three dots when talking so I am grateful for that. It is static now.

**Comment by 3v1n0** [comment]
I can't run steam currently (I'm affected by [this issue](https://steamcommunity.com/discussions/forum/1/3790379982478123731/)), however I've tried to manually create an indicator that loads `~/.steam/public/steam_tray_mono.png` and I found the issue.
