### ISSUE TITLE
Desaturation not working

### ISSUE THREAD

**Issue by somepaulo** [ubuntu/gnome-shell-extension-appindicator#404]
Since the last update the extension stopped desaturating icons. Changing the slider position in settings has no effect on the icons.
I have some symbolic icons defined as custom for the apps I use. The icons themselves are black. Desaturation made them white. Now they're black again no matter the setting.

**Comment by 3v1n0** [comment]
Weird, it works correctly to me:

![image](https://user-images.githubusercontent.com/345675/222587071-10b416e5-2df1-41d8-b1cd-1e411098da58.png)

And these are all the three types of icons we support (file icon, pixmap and tray)

**Comment by somepaulo** [comment]
I did some checks, and it becomes weirder.
All my settings have been unchanged for ages, and desaturation used to make black icons white. Now they remain black.
If I remove my custom icon settings and let the tray use the original full-color icons, desaturation works.

![Screenshot from 2023-03-03 10-36-15](https://user-images.githubusercontent.com/15643750/222702787-58719796-fac4-4d5b-8c00-4d60a49f4fce.png)

![Screenshot from 2023-03-03 10-54-16](https://user-images.githubusercontent.com/15643750/222702903-380265b5-a67a-4ab9-9d01-c2840b9ffe18.png)

As soon as I put my setting back to use a symbolic icon (same icon theme, same format - .svg) desaturation stops working, and the icon remains black no matter the setting. It used to become white until last week.

![Screenshot from 2023-03-03 10-37-53](https://user-images.githubusercontent.com/15643750/222703083-c009c689-d803-468f-93bd-6047c2204032.png)

![Screenshot from 2023-03-03 10-38-11](https://user-images.githubusercontent.com/15643750/222703112-27c96abd-2104-43b9-baef-67e248a277f6.png)

The icons themselves haven't changed (I'm the developer of the icon theme). The same happens if I use a symbolic icon from Adwaita.

![Screenshot from 2023-03-03 10-51-41](https://user-images.githubusercontent.com/15643750/222703257-b3f797a8-f456-41db-b4ba-0938c8c0acb5.png)

This started after an extension update, although there were other system updates around the same time.

I'm using firewalld for the examples above, but the same happens to all other icons.

**Comment by 3v1n0** [comment]
Please, check #406 that handles this problem (it was not due to desaturation, but to the fact that the theme colors were not being applied to the loaded symbolic icons).

**Comment by somepaulo** [comment]
> Please, check https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/406

Yup, #406 solves this. Thank you!
