### ISSUE TITLE
Extension broken on latest gnome-shell (main)

### ISSUE THREAD

**Issue by kubrickfr** [ubuntu/gnome-shell-extension-appindicator#408]
See https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6465#note_1688903 for the details, it looks like some changes are going to be required to make this work again...

**Comment by 3v1n0** [comment]
I should have handled this already in #407 few days ago so I should handle that there.

**Comment by 3v1n0** [comment]
Also I needed https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2671 so that's now in.

**Comment by kubrickfr** [comment]
Works for me, thanks!
