### ISSUE TITLE
Is it possible that this extension works with cinnamon?

### ISSUE THREAD

**Issue by jm18919** [ubuntu/gnome-shell-extension-appindicator#41]
Is it possible that this extension is compatible with Cinnamon after some changes? 
If the answer is NO, can anyone tell me briefly how this extension works? I have tried to read some of the source codes. But without knowing the idea behind them, I have lost in details.
I do know an idea that can implement global menu bar in X: XEmbed. Does this extension use XEmbed?

**Comment by lestcape** [comment]
https://github.com/linuxmint/Cinnamon/issues/3032#issuecomment-76527610
