### ISSUE TITLE
vorta icon is not completely loaded at startup

### ISSUE THREAD

**Issue by luca-e075e** [ubuntu/gnome-shell-extension-appindicator#410]
Since the last update, Vorta icon is not completely loaded when the shell starts.

If I quit Vorta and reopen it there is no issue, the same removing Vorta option “Automatically start Vorta at login” and open it manually after login

The three dots icons appear when apps start loading, but they will be replaced by their respective icons

AppIndicator 50
Gnome shell 3.38.5
Debian 11 stable
Vorta 0.7.5-1 [from debian repository](https://packages.debian.org/bullseye/vorta)

# the 3 dots is Vorta
![vorta icon not loaded](https://user-images.githubusercontent.com/15078341/223430995-2daeb7b7-d38f-4878-bfa4-87fb56eb2314.png)

# it should looks like this
![Vorta icon](https://user-images.githubusercontent.com/15078341/223431663-77470f21-6428-4076-9fdf-e4a25cdea69e.png)

**Comment by stuarthayhurst** [comment]
Did a bisect, da020e361a1ebdbbdd70754f7e87755239b28803 is guilty

**Comment by 3v1n0** [comment]
Please check if https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/412 helps with this

**Comment by JOH451** [comment]
That seems to have resolved the problem for me.

**Comment by yochananmarqos** [comment]
@3v1n0 Thanks. By the way, the issue was only affecting Qt applications.

**Comment by stuarthayhurst** [comment]
> Thanks. By the way, the issue was only affecting Qt applications.

I only have GTK apps on my system and this was affecting me, so I don't know if that's exactly correct

**Comment by JOH451** [comment]
> > Thanks. By the way, the issue was only affecting Qt applications.
> 
> I only have GTK apps on my system and this was affecting me, so I don't know if that's exactly correct

It was a GTK application for me as well. I think it's a matter of how the application interacts with the Gnome shell rather than the libraries it uses to do it.

**Comment by Apacelus** [comment]
Im still having this issue on fedora 37, extension version 53
