### ISSUE TITLE
3 icons replaced by dots

### ISSUE THREAD

**Issue by patricklibert** [ubuntu/gnome-shell-extension-appindicator#411]
Ubuntu 22.04

The latest update today totally screwed things up.

Deluge, ULauncher and RadioTray trayicons are replaced with 3 dots icons.

See picture in attachment

![kstatus](https://user-images.githubusercontent.com/647670/223489965-e814ddf1-9bff-4a2b-bd6f-4d4fac25de74.png)

**Comment by 3v1n0** [comment]
Please provide a log, however a `git bisect` could help to figure out the guilty commit.

**Comment by 3v1n0** [comment]
Duplicate of #410
