### ISSUE TITLE
No legacy icons visible (pidgin) on Fedora 38 and GNOME 44

### ISSUE THREAD

**Issue by vbenes** [ubuntu/gnome-shell-extension-appindicator#420]
Hi, some time ago pidgin icon somehow disappeared, no idea why. I see empty space, I can click it, just the icon is not there. Any hint where should I look for it?

this is what I have:
/usr/share/pixmaps/pidgin/tray
/usr/share/pixmaps/pidgin/tray/16
/usr/share/pixmaps/pidgin/tray/16/available_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/away_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/busy_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/connecting_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/extended-away_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/invisible_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/message_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/offline_4bit.ico
/usr/share/pixmaps/pidgin/tray/hicolor
/usr/share/pixmaps/pidgin/tray/hicolor/16x16
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/index.theme

no errors visible in journal, icon size 24, opacity 240, the rest 0s, alignment to right, Enable legacy tray icons enabled. 

Thank you!

**Comment by SashaPGT** [comment]
This happens with apps running via Wine too. Even worse, clicking the empty space doesn't bring up right-click menu as it should be, forcing us to kill the app when we need to close them instead of right-clicking the icon and closing gracefully.

**Comment by 3v1n0** [comment]
I think it's due to the fact you've not this fix included in your distro yet: https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/20a81d786697f40880e81d867453b1bad9524ec1
