### ISSUE TITLE
Fedora 36/37 - Keepass - tray icon disapears after locking desktop

### ISSUE THREAD

**Issue by mvrk69** [ubuntu/gnome-shell-extension-appindicator#421]
Hi,

I'm experiencing a problem with appindicator and Keepass2, after i lock my desktop and then unlock, the tray icon from Keepass2 disappears. 

It worked fine until appindicator v42, started failing with 43+

The only thing i can see on the system logs is this:

Mar 29 13:01:12 d6y0fb3-laptop keepass.desktop[248320]: XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
Mar 29 13:01:12 d6y0fb3-laptop keepass.desktop[248320]: xdo_get_active_window reported an error

Anyone has any idea what might be the problem?

**Comment by 3v1n0** [comment]
This is in the mono version, right?

I can definitely reproduce this in keepass2 though.

**Comment by mvrk69** [comment]
yes correct, keepass2

**Comment by ychromosome** [comment]
you should not use keepass2 on linux, because it shows any password in journal.

**Comment by mvrk69** [comment]
That security issue doesn't seem to be present on F36 with keepass 2.49

**Comment by ychromosome** [comment]
I know I am quite offtopic, but I had it with F36 which made me change to keepassxc.
Anyway F36 will be EOL in less than three weeks and keepass is orphaned with starting of F37, so you basically should try to find a replacement, that hopefully does not have this bug.

**Comment by mvrk69** [comment]
I tested today with v53 on F37 and no longer happens.
