### ISSUE TITLE
GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow

### ISSUE THREAD

**Issue by gtirloni** [ubuntu/gnome-shell-extension-appindicator#434]
I'm not sure if this is important or not but thought I would report it here in case someone has a clue.

Every time I click on the Slack icon (flatpak-installed), this shows up in journalctl:

```
$ journalctl -f -o cat /usr/bin/gnome-shell
JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
### Promise created here: ###
sendAboutToShow@/home/username/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:501:48
sendAboutToShow@/home/username/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:197:22
_onMenuOpened@/home/username/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:935:28
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
open@resource:///org/gnome/shell/ui/popupMenu.js:927:14
toggle@resource:///org/gnome/shell/ui/popupMenu.js:800:18
vfunc_button_press_event@/home/username/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/indicatorStatusIcon.js:425:27
```

It does not happen with the Zoom icon (also flatpak-installed) or the SafeNet eToken client (RPM-installed).

**Comment by 3v1n0** [comment]
See https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/429#issuecomment-1516232202 it should be an app-issue.

**Comment by andreasfernandez** [comment]
> See [#429 (comment)](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/429#issuecomment-1516232202) it should be an app-issue.

In the linked case it happens with Discord, being in a voice channel and the input state changes (start/stop speaking). Apparently, Discord tries to change its icon which is broken since ever anyway.

**Comment by stuarthayhurst** [comment]
Oops, I seem to have duplicated this with #445, didn't see this when I submitted that

However, it does appear that a lot of other users are having the same problem

**Comment by 3v1n0** [comment]
Closing this as per #525. Note that this has never been a problem or a crash, just a log message with extended stack trace.
