### ISSUE TITLE
invisible big icon

### ISSUE THREAD

**Issue by deepdows** [ubuntu/gnome-shell-extension-appindicator#435]
After upgrading ubuntu from 22.10 to 23.04 there is a problem happened: there is an area that is not clickable. After doing some research I found out that it is because of gnome-shell-extension-appindicator (after disabling it).
Here more information on my problem (with screenshots and video)
https://askubuntu.com/questions/1464483/upgrade-22-10-to-23-04-one-area-is-not-clickable

**Comment by 3v1n0** [comment]
You can workaround this by disabling the legacy tray icons support in settings, however I feel that's more a GNOME shell bug more than an extension issue.

Are you using Wayland or X11, and do you have any application using legacy tray icons?

Also provide the output of `xwininfo` and `xprop` selecting that not-clickable area.

**Comment by deepdows** [comment]
> You can workaround this by disabling the legacy tray icons support in settings
After disabling the extension (and rebooting), this area started to be clickable 

> Are you using Wayland or X11
I use X11

> do you have any application using legacy tray icons
Anydesk, skype, telegram, so on...
please check out this video also
Found out that this window is an invisible application icon. When I change workplace it becomes visible.
https://drive.google.com/file/d/1BLHsBJe1kv76ijC0-1dXnUGyEuwz2LO8/view?usp=share_link

xwininfo: Window id: 0x40354e (has no name)

  Absolute upper-left X:  1676
  Absolute upper-left Y:  5
  Relative upper-left X:  1676
  Relative upper-left Y:  5
  Width: 200
  Height: 200
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +1676+5  -44+5  -44-875  +1676-875
  -geometry 200x200-44+5
  
  xprop:
 _GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW

**Comment by deepdows** [comment]
Looks like this is anydesk issue, after deleting it, the problem was solved.
