### ISSUE TITLE
wine6.0 apps tray not work

### ISSUE THREAD

**Issue by XAVIER2020-CLOUD** [ubuntu/gnome-shell-extension-appindicator#436]
Hi, 
I installed a wine6.0 app (wechat ) on my fedora 37, I update the system to the fadora 38 , the trouble arise：

When I turn on "Enable Legacy Tray Icons support",  the tray become transparent and cannot be clicked .like the pic:
![2023-04-22 02-46-19屏幕截图](https://user-images.githubusercontent.com/66563879/233726478-6d14840e-a87f-43e8-b94c-d370bc96c745.png)

But, when I turn off "Enable Legacy Tray Icons support",  the tray cannot appear on the top and wine tray loader appeared on the desktop

how can I let wine tray works well again, dudes

**Comment by 3v1n0** [comment]
This is a GNOME shell issue, you need Shell 44.1 to get that fixed, see: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2684
