### ISSUE TITLE
Changing click behaviour 

### ISSUE THREAD

**Issue by gzpr** [ubuntu/gnome-shell-extension-appindicator#442]
Is it possible to change the single left click behavior so it opens the application window instead of the menu?

**Comment by 3v1n0** [comment]
No, I'm sorry.

It would technically possible to do that for some applications supporting Activation, but great majority of them don't and StatusNotifierItem is designed to always show menus and have clear behavior all the times.

**Comment by t00** [comment]
Could we instead ask for an option to simply swap double click and single left click behavior?

Currently double click opens the window for quite a few applications (in my case majority - open snitch, bitwarden, blueman) while it opens up the menu only for steam. Swapping them around would just make it easier to access the application window while keeping double click doing some "activation" which has the same effect as pressing right mouse button.
