### ISSUE TITLE
wine6.0 apps tray icon has black background

### ISSUE THREAD

**Issue by ypli0629** [ubuntu/gnome-shell-extension-appindicator#446]
wine6.0 apps tray icon has black background and no response after clicking tray icon

gnome-shell: 44.2

![image](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/22133189/64ceb7cb-cf8e-489c-84c3-79e87949f8c8)

**Comment by KingUnderSky** [comment]
For me, Lutris apps

Wine: lutris-ge-lol-8.6-1-x86_64
gnome-shell: 44.2

![image](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/10741915/c5a7f5af-0970-4d3c-affe-098cae62bb44)

**Comment by badlydrawnface** [comment]
ditto, uplay running trackmania 2020 through steam

GE-Proton 8.4
Fedora 38 Workstation
GNOME 44.2 Wayland
Extension version: 53

![image](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/53501005/a174d004-8368-4be3-82b3-4a2c1fd4194c)

**Comment by mtricht** [comment]
A "workaround" is to disable legacy tray icons support in the extensions settings, so you get the wine system tray window which has a working system tray. Not the prettiest but at least functional.

**Comment by 238Ver** [comment]
It is an issue. Unclickable wine tray icons also cause some trouble.

**Comment by joezhouchenye** [comment]
Using Tray Icons Reloaded Extension, the wine apps can be double-left-clicked to open the window and double-right-clicked to open the context menu. However, all tray icons have a black background if I switched the extension and Steam's context menu displays as an old theme.
