### ISSUE TITLE
[Feature Request] Add GNOME 45 Support

### ISSUE THREAD

**Issue by git-Hmmm** [ubuntu/gnome-shell-extension-appindicator#454]
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

check: [gjs.guide/extensions/upgrading/gnome-shell-45.html](https://gjs.guide/extensions/upgrading/gnome-shell-45.html)

**Comment by Koitharu** [comment]
Happens again after update:

```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  @file:///usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/prefs.js:25:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  ```

**Comment by yochananmarqos** [comment]
@3v1n0 I'm seeing the same error as @Koitharu. Maybe a new issue should be created?

**Comment by stouracp** [comment]
I can see Util.DBusProxy is undefined on Fedora 39 Gnome 45

**Comment by AsciiWolf** [comment]
> I can see Util.DBusProxy is undefined on Fedora 39 Gnome 45

Even with gnome-shell-extension-appindicator version 57? I have just tested the extension on latest Fedora Rawhide and it seems to work fine.

**Comment by stouracp** [comment]
So, version, installed from git, seems working, the case is, as there is a version mismatch, it is asking for update from extensions.gnome.org to version 56 now.

**Comment by stouracp** [comment]
When will version 57 relesed at extensions.gnome.org?

**Comment by stouracp** [comment]
small update of metadata.json made gnome-shell detects this version as 57, and autoupdates are not breaking it anymore.
