### ISSUE TITLE
New release incompatible with GNOME 44.3.

### ISSUE THREAD

**Issue by petcat30** [ubuntu/gnome-shell-extension-appindicator#456]
I'm running Arch with version 44.3 of GNOME. After updating to the new release of this extension it no longer loads and in the Extensions app it says "The extension is incompatible with the current GNOME version"

EDIT: I see a bug report was opened here as well: https://bugs.archlinux.org/task/79401?project=1&string=gnome-shell-extension-appindicator

**Comment by Whayme** [comment]
Also experiencing this.

**Comment by yuelwish** [comment]
me too

OS: EndeavourOS Linux x86_64
DE: GNOME 44.3
WM: Mutter 
Kernel: 6.1.46-1-lts


The settings of extension appindicatorsupport@rgcjonas.gmail.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by 3v1n0** [comment]
As visible in [metadata](https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/metadata.json), latest version is only supporting gnome 45.

More info at https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

As per this, no further main updates will happen on gnome pre-45 versions

**Comment by D3vil0p3r** [comment]
@3v1n0 is still in beta release... I think it is not good to release a "stable" version of a GNOME extension for a GNOME version that is still in beta...

**Comment by 3v1n0** [comment]
The extension is released *only* for GNOME 45, so packagers must be aware that they should not update it for everybody, and adapt dependencies/breaks accordingly.

It's a distributor error if this happen.

Sadly GNOME extensions have no concept of beta releases, so there's no point to mark them as such in github either.
