### ISSUE TITLE
Actually release v57

### ISSUE THREAD

**Issue by AsciiWolf** [ubuntu/gnome-shell-extension-appindicator#462]
It looks like that there is just a [tag](https://github.com/ubuntu/gnome-shell-extension-appindicator/tags) for v57, not an actual release in [Releases](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases).

@3v1n0 Please, also consider making an release for v57. Thanks!

**Comment by 3v1n0** [comment]
Done https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v57

**Comment by stuarthayhurst** [comment]
Is it also missing a release on extensions.gnome.org?

**Comment by AsciiWolf** [comment]
> Is it also missing a release on extensions.gnome.org?

I have created a new ticket for this here: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/465
