### ISSUE TITLE
Version 57 missing on extensions.gnome.org

### ISSUE THREAD

**Issue by AsciiWolf** [ubuntu/gnome-shell-extension-appindicator#465]
gnome-shell-extension-appindicator is still at version 56 [on extensions.gnome.org](https://extensions.gnome.org/extension/615/appindicator-support/). Please, consider uploading a new build there. Thanks!

**Comment by ArtikusHG** [comment]
+1, imo this should be a bit higher on the priority list - version 56 has the annoying ```Util.DBusProxy is undefined``` bug on GNOME 45.

**Comment by Aqua1ung** [comment]
Please upload ver. 57 on extensions.gnome.org!

And many thanks for a wonderful piece of software!

**Comment by superclarkk** [comment]
+1

**Comment by justanotherinternetguy** [comment]
+1

**Comment by yc-codes** [comment]
+1

**Comment by 3v1n0** [comment]
Sorry, it took a while, it's there now. Wait for it being reviewed and you should get it.
