### ISSUE TITLE
please add Gnome 46 support

### ISSUE THREAD

**Issue by bam80** [ubuntu/gnome-shell-extension-appindicator#510]

**Comment by DeN-AlB** [comment]
Installed Fedora Linux 40 Prerelease with Gnome 46 yesterday. Please add support! :)

**Comment by LeeRoyManea** [comment]
+1

**Comment by pedro-hro** [comment]
+1

**Comment by Jfjrbrbfjf** [comment]
+1

**Comment by pavangayakwad** [comment]
Tried changing the shell-version to 46 in metadata.json, extension made gnome shell crash. so, yeah.. please check and include Gnome 46 support. 

Thanks.

**Comment by bulletmark** [comment]
If I disable version validation via https://extensions.gnome.org/local/ then this extension works fine on Arch where GNOME has updated to 46. So seems to me to only require the metadata change?

**Comment by xuanruiqi** [comment]
Looks like the metadata's already changed, it just needs a new release.

**Comment by xuanruiqi** [comment]
Yeah, building git master works fine for me.

**Comment by Facni** [comment]
+1

**Comment by szw0407** [comment]
In case anyone not quite familiar with GNOME extensions, including me myself, you may consider doing this:

`vim ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/metadata.json`, 
and add '46' to `shell-version`.

**Comment by bulletmark** [comment]
Or just disable version validation for all extensions with:

     gsettings set org.gnome.shell disable-extension-version-validation true

Wait a month or so until they are all updated then reset that validation to default:

    gsettings reset org.gnome.shell disable-extension-version-validation

**Comment by DeN-AlB** [comment]
Works like a charm, @bulletmark ! Thanks! :+1:

**Comment by bam80** [comment]
Or if it's as simple, we do a release maybe?

**Comment by A404M** [comment]
@bam80 please do a release
Many people don't come over to Github to build for themselves

**Comment by DeN-AlB** [comment]
Still no official support for Gnome 46 ... :disappointed:

**Comment by A404M** [comment]
I don't know why they don't just make a release for Gnome 46
Is there any reason not to do so?
It works in Gnome 46 out of the box
So why not to do a release?

**Comment by matdave** [comment]
> I don't know why they don't just make a release for Gnome 46 Is there any reason not to do so? It works in Gnome 46 out of the box So why not to do a release?

It's maintained by Ubuntu, which has no real reason to update until they support Gnome 46

**Comment by DeN-AlB** [comment]
Maybe it's time for a fork? :thinking:

**Comment by A404M** [comment]
> Maybe it's time for a fork? 🤔

If anyone made a fork I will help voluntarily

**Comment by DeN-AlB** [comment]
Unfortunately, I don't know what to do and how to do this. :disappointed:

**Comment by Deuchnord** [comment]
> > I don't know why they don't just make a release for Gnome 46 Is there any reason not to do so? It works in Gnome 46 out of the box So why not to do a release?
> 
> It's maintained by Ubuntu, which has no real reason to update until they support Gnome 46

Then this extension should already be updated since a long time now, as [Ubuntu 24.04 is expected for this month will use GNOME 46](https://linuxconfig.org/ubuntu-24-04-lts-vs-22-04-lts-a-comparison-guide-and-whats-new).

**Comment by A404M** [comment]
> > > I don't know why they don't just make a release for Gnome 46 Is there any reason not to do so? It works in Gnome 46 out of the box So why not to do a release?
> > 
> > It's maintained by Ubuntu, which has no real reason to update until they support Gnome 46
> 
> Then this extension should already be updated since a long time now, as [Ubuntu 24.04 is expected for this month will use GNOME 46](https://linuxconfig.org/ubuntu-24-04-lts-vs-22-04-lts-a-comparison-guide-and-whats-new).

Yes but it is not yet published
Arch repository has updated this extension yesterday and I'm so happy about it
I hope they update it on extensions.gnome.org too

**Comment by Hydranet** [comment]
> Arch repository has updated this extension yesterday and I'm so happy about it

I'm curious which Arch repository you are talking about because that extension is not in the default repos, the only thing Arch I can find about it is that there is a PKGBUILD of it that builds off of the master branch.

**Comment by escape0707** [comment]
@Hydranet I guess they means: https://gitlab.archlinux.org/archlinux/packaging/packages/gnome-shell-extension-appindicator

**Comment by Hydranet** [comment]
> @Hydranet I guess they mean patches here: https://gitlab.archlinux.org/archlinux/packaging/packages/gnome-shell-extension-appindicator

It seems that extension made it to to the extra repo, I never knew that. Thanks!

**Comment by DeN-AlB** [comment]
Good to know! Thanks, too.

**Comment by Hydranet** [comment]
> > It seems that extension made it to to the extra repo, I never knew that. Thanks!
> 
> But it is version 57, too, that doesn't support Gnome 46. https://archlinux.org/packages/extra/any/gnome-shell-extension-appindicator/

It works though.

**Comment by DeN-AlB** [comment]
> It works though.

I didn't test it. But yes, it works! The only difference is that it's now a system extension and not a user extension anymore in Extension Manager. But that's ok. :+1:

**Comment by a4orce84** [comment]
Hello Everyone,

Sorry for the newb question, but I uninstalled this extension in the "Extensions Manager" and am unsure how to reinstall it (so I can use it by updating the metadata.json file). Searching in the Extensions Manager, I cannot seem to find it either.

Can anyone give me some quick and dirty steps on how to reinstall this extension please? Thanks!

**Comment by Hydranet** [comment]
> Can anyone give me some quick and dirty steps on how to reinstall this extension please? Thanks!

https://github.com/ubuntu/gnome-shell-extension-appindicator?tab=readme-ov-file#installation

Or if you are using an Arch-based distribution you can install it from the reps "gnome-shell-extension-appindicator".

**Comment by Aman9das** [comment]
@3v1n0 ping

**Comment by laichiaheng** [comment]
> > > It seems that extension made it to to the extra repo, I never knew that. Thanks!
> > 
> > 
> > But it is version 57, too, that doesn't support Gnome 46. https://archlinux.org/packages/extra/any/gnome-shell-extension-appindicator/
> 
> It works though.

It never works.
![圖片](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/9532105/b0b9dcfb-aab7-4b19-b214-88a737ac1fac)

**Comment by laichiaheng** [comment]
> > > > It seems that extension made it to to the extra repo, I never knew that. Thanks!
> > > 
> > > 
> > > But it is version 57, too, that doesn't support Gnome 46. https://archlinux.org/packages/extra/any/gnome-shell-extension-appindicator/
> > 
> > 
> > It works though.
> 
> It never works. ![圖片](https://private-user-images.githubusercontent.com/9532105/323043835-b0b9dcfb-aab7-4b19-b214-88a737ac1fac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTkyMDQsIm5iZiI6MTcxMzMxODkwNCwicGF0aCI6Ii85NTMyMTA1LzMyMzA0MzgzNS1iMGI5ZGNmYi1hYWI3LTRiMTktYjIxNC04OGE3MzdhYzFmYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMDE1NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBiNzczZDc1NTUyYjNlYTE5ODZlZTk3NzJmYTk2N2VkNTFlZTUyNjMwYjdjNjkzZWQ4NDViZjUyZDI2ZDgxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0RncGLSQwqdvp2-MeXJ2C8dkgguGFQzNyImsOh4N4qo) ![圖片](https://private-user-images.githubusercontent.com/9532105/323043948-ebc52c91-627c-40ee-9da7-34ca34d03257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTkyMDQsIm5iZiI6MTcxMzMxODkwNCwicGF0aCI6Ii85NTMyMTA1LzMyMzA0Mzk0OC1lYmM1MmM5MS02MjdjLTQwZWUtOWRhNy0zNGNhMzRkMDMyNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMDE1NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNhY2NlMDJkNDg4YWYzZTEyNWUwOGJlYzYwNzdkNTA5OTNjYmFlYmQ3ZjhlMGIxYzE3NGIyZDZjOTAxYTExOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K28frf8j5Q1aC3KtoQSYABIgiTFPGPOz8yJV-6Y4MwQ)

I just realized that I need to remove its files in `~/.local/share/gnome-shell/extensions/`

**Comment by Aqua1ung** [comment]
C'mon, guys, any indication when this'll trickle down to [ego](https://extensions.gnome.org/extension/615/appindicator-support/)?

**Comment by DeN-AlB** [comment]
@Aqua1ung 
Which Distribution are you using? Did you look into the repos, if there is a working version of the extension?
I know that Arch Linux and Fedora Linux are offering that extension in their own repos.

https://archlinux.org/packages/extra/any/gnome-shell-extension-appindicator/
https://packages.fedoraproject.org/pkgs/gnome-shell-extension-appindicator/gnome-shell-extension-appindicator/

**Comment by Aqua1ung** [comment]
> @Aqua1ung Which Distribution are you using? Did you look into the repos, if there is a working version of the extension? I know that Arch Linux and Fedora Linux are offering that extension in their own repos.

Thank you. No, [my distro](https://www.clearlinux.org/) does not offer this extension (or any GNOME extension whatsoever) in its repo.

**Comment by 3v1n0** [comment]
Sorry, this has been an intense cycle, so it took more than expected to prepare the release, after the various contributions (thanks!) to address various things.

The new release is ready for download (if you want install it via `gnome-extensions install`) and once [reviewed](https://extensions.gnome.org/review/53899) will be available in e.g.o too.
