### ISSUE TITLE
Regression: Jammy to Noble, set_label no longer functions

### ISSUE THREAD

**Issue by theofficialgman** [ubuntu/gnome-shell-extension-appindicator#514]
In ubuntu jammy and previous releases, set_label can be used to set the text to display instead of an appindicator icon. In ubuntu noble set_label no longer functions at all.
https://gjs-docs.gnome.org/appindicator301~0.1/appindicator3.indicator#method-set_label

https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/2059818

**Comment by tstsrt** [comment]
I believe this is caused by the deprecated `Clutter.Container.add_actor` being removed in Gnome 46. #503 should fix this. Maintainers, please review said PR. @3v1n0

**Comment by theofficialgman** [comment]
@tstsrt @3v1n0 @sergio-costas can confirm that PR fixes this issue. Please merge and update the extension before Noble releases

**Comment by theofficialgman** [comment]
CC: @jbicha (because it looks like you have taken over maintenance for that package from Marco Trevisan) ^

**Comment by 3v1n0** [comment]
Handled via https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/503
