### ISSUE TITLE
First click after startup is treated as both a single click and a double click

### ISSUE THREAD

**Issue by jingw** [ubuntu/gnome-shell-extension-appindicator#516]
### Current behavior
After the first single click, two actions trigger:
- single click -> open menu
- code is confused into thinking there's a double click -> open app

![Screenshot from 2024-04-04 21-43-49](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/2019426/5dbda36f-e8f1-4ea1-b1fc-2914e4d152c1)

### Expected behavior: single click should only open menu
![Screenshot from 2024-04-04 21-44-33](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/2019426/f5a29419-d260-4743-bf35-382d7f3e221b)

### Code diagnosis
Looking at the code, the problem is that both `vfunc_button_press_event` and `vfunc_button_release_event` call `_maybeHandleDoubleClick` the first time around, so a press+release becomes a double click. But the second time, `this._indicator.supportsActivation` has been set to `true` instead of `undefined`, so `vfunc_button_release_event` doesn't trigger the double click.
https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/03a7412e604670597dfd5d8a70fcc90ebed48b7b/indicatorStatusIcon.js#L423-L428

I can hack the code to make the issue go away with an extra `this._indicator.supportsActivation !== undefined`, but I'm not sure what the intent of this code was, so I'm not sure what the right fix is.
```
    vfunc_button_release_event(event) {
        if (this._indicator.supportsActivation !== undefined && !this._indicator.supportsActivation)
            return this._maybeHandleDoubleClick(event);

        return Clutter.EVENT_PROPAGATE;
    }
```

The current behavior of `supportsActivation == false` seems strange:
- Any single click hits `_maybeHandleDoubleClick` in both press and release
- `_maybeHandleDoubleClick` short circuits with `return Clutter.EVENT_PROPAGATE`, making the logic in vfunc_button_release_event pointless. https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/03a7412e604670597dfd5d8a70fcc90ebed48b7b/indicatorStatusIcon.js#L355-L357

I suspect the right fix might just be to delete the `vfunc_button_release_event` logic. I confirm deleting the whole function works for me, but I unfortunately don't seem to have any apps for which `supportsActivation == false`, so I don't know how to test it works in general.

**Comment by PylotLight** [comment]
Ideally it should work the opposite, that LClick is open the tray window and RClick is open the menu, and DClick is activate/open application. 3 Separate events from 3 separate actions as currently LClick is treated same as RClick.

**Comment by PylotLight** [comment]
After understanding the framework I'm working with a bit more (A golang app
that consumes org.kde.StatusNotifierItem.Activate).
I think I would prefer:

   - left click ->  this._indicator.open (after a delay)
   - right click -> this.menu.toggle
   - double click -> this._indicator.open

You already have RClick for menu toggle, so don't need LClick for that as
well. If there's a preferred discussion area for this topic lmk, as
obviously this PR is not the correct place for this.
