### ISSUE TITLE
Single Click cannot open the menu but double click works fine

### ISSUE THREAD

**Issue by asd-a** [ubuntu/gnome-shell-extension-appindicator#523]
It seems that some tray icon cannot open the menu (maybe the legacy one), and the double click works fine.

it only occurs when the app starts after this ext.

I restarted the ext this problem fixed but single click will startup the app  #516 

tested the `linuxqq` from aur in arch linux gnome 46, which has this problem

**Comment by theofficialgman** [comment]
likely duplicate of https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/515

**Comment by 3v1n0** [comment]
I think it's definitely a duplicate, not much we can do at this level.
