### ISSUE TITLE
Delay with app settings dropdown only when left-clicking

### ISSUE THREAD

**Issue by P-Jay357** [ubuntu/gnome-shell-extension-appindicator#535]
If I have something like Vorta in the top tray and left-click it, it takes 0.5 seconds or more to open the dropdown menu. If I right-click, it drops down instantly. This isn't the case for any of the default GNOME top-bar stuff like the clock or quick settings, so it makes me wonder if it's an issue with he extension itself (as this doesn't just happen when it's Vorta in the top tray).

Here's a video of this. It's hard to tell though as you can't see when I click, but when it opens and closes rapidly, I can only do this by right-clicking, the delays between it opening is just me waiting after left-clicking before it opens.

https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/43815586/57abd025-c07f-4635-9c1c-f43517fe9a14

I am running Fedora Workstation 40, GNOME version 46 and the extension's version is 58,

**Comment by Dannflower** [comment]
I am running the same configuration and noticed this as well. When left-clicking an app indicator in the top-bar there's like a 3/4 second delay before the menu displays. Right-clicking it instead causes it to appear instantly.

Interestingly, Steam's indicator does not exhibit this problem and opens instantly with a left- or right-click.

**Comment by 3v1n0** [comment]
Sadly this is the only way we have to support double-click on indicators that do it. We avoid using the delay in case the indicator has no support for it, but there's no way to figure it out until trying the first time.

**Comment by ztefn** [comment]
> We avoid using the delay in case the indicator has no support for it, but there's no way to figure it out until trying the first time.

@3v1n0 According to [the spec](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/) there is a way to figure it out in advance:

`org.freedesktop.StatusNotifierItem.ItemIsMenu`

BOOL: The item only support the context menu, the visualization should prefer showing the menu or sending ContextMenu() instead of Activate()
