### ISSUE TITLE
problem Gnome Shell 3.18

### ISSUE THREAD

**Issue by Nasreddine** [ubuntu/gnome-shell-extension-appindicator#60]
Hi,
When I activate the extension, gnome-shell logout automatically.
I'm using it on ubuntu 15.10.

**Comment by axfelix** [comment]
Working fine for me under 3.18 on Arch (well, except for the other issue I have open)

I have noticed that occasionally gnome-shell looks like it's restarting itself on login and I suppose it's possible that lightdm (Ubuntu) would be handling that differently from gdm ("pure" gnome configs like mine) if there is in fact a crash.

**Comment by darthoctopus** [comment]
Seconded: this extension makes gnome-shell segfault upon screen unlock (I'm on 3.18)

**Comment by jhasse** [comment]
Which apps are using the appindicator?

**Comment by jhasse** [comment]
Please re-open this issue if you can still reproduce it.
