### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by ninjagoat** [ubuntu/gnome-shell-extension-appindicator#68]
I use Papirus theme and the icons appear too small. They look alright with TopIcons but I don't prefer that extension as it does not show any text attached to an indicator.

So, would you mind adding a setting for icon size? Or else please tell me where to modify the code?

**Comment by jhasse** [comment]
Add the line

```
icon_size += 8;
```

here: https://github.com/rgcjonas/gnome-shell-extension-appindicator/blob/master/appIndicator.js#L221

**Comment by cra0zy** [comment]
Can you add settings panel to control icon size?

**Comment by jhasse** [comment]
I'll look into that, but not right now. PRs welcome :)

**Comment by ninjagoat** [comment]
Thank you very much @jhasse

**Comment by owais** [comment]
This is still an issue on Ubuntu 17.10 stock install. I tested on an XPS 13 with HiDPI screen.

**Comment by JasonLG1979** [comment]
You shouldn't manually set the icon size, you should instead use the built in style classes.

**Comment by jhasse** [comment]
Do you mean CSS classes?

**Comment by JasonLG1979** [comment]
> Do you mean CSS classes?

Yes

**Comment by JasonLG1979** [comment]
If you use the standard style classes you don't have to worry about the size of things for the most part.

**Comment by JasonLG1979** [comment]
You should already be getting the panel-button style class for free if/when you extend PanelMenu.Button for your indicator icons. You shouldn't need to manually set the icon size.

**Comment by owais** [comment]
![screenshot from 2017-09-06 15-21-37](https://user-images.githubusercontent.com/46186/30105818-532ea392-9317-11e7-8f00-f4c310040d73.png)

Current look on XPS 13 HD (1920x1080) display.

@didrocks FYI

**Comment by owais** [comment]
![screenshot from 2017-09-06 15-25-34](https://user-images.githubusercontent.com/46186/30105950-a7b52b0c-9317-11e7-9e75-2c90577fc172.png)

OK. It looks much worse in real life. For some reason it becomes more clear in screenshots but IRL the icons hardly grab attention in unread state.

**Comment by JasonLG1979** [comment]
It also depends on how much padding is around the icon in the actual icon svg. If for example it's a 16x16 svg but the icon itself has 1px of padding all around it then the icon would actually be whatever % smaller. Not much you can do about that.

**Comment by jhasse** [comment]
Steam icon looks fine though. Is Dropbox with `XDG_CURRENT_DESKTOP=Unity`?

I'll install Ubuntu 17.10 tonight and also test this.

**Comment by orschiro** [comment]
I have this problem with Telegram Desktop.

![image](https://user-images.githubusercontent.com/170947/31828964-263528b2-b5bc-11e7-82ae-fdc2d7bc7807.png)

**Comment by jhasse** [comment]
I just tried on a fresh updated Ubuntu 17.10: Dropbox' and Telegram's icons are the correct size when started with `XDG_CURRENT_DESKTOP=Unity`, so I guess this is some bug in Qt?

**Comment by jhasse** [comment]
Okay I've found out that this has to do with #95.

Before:
![before pr](https://user-images.githubusercontent.com/80071/31842035-792ca8da-b5ec-11e7-96cb-bbed4101bcb6.png)

After:
![after pr](https://user-images.githubusercontent.com/80071/31842037-7dc4e092-b5ec-11e7-83ce-392395381357.png)

My simple solution would be to increase the icon size by 2 and keep the PR, which would look like this:
![plus 2](https://user-images.githubusercontent.com/80071/31842040-8188f7c2-b5ec-11e7-9a64-aaa36d7cf0a5.png)

Opinions?

**Comment by LiamDawe** [comment]
That does look vastly better, but still, I think the space between the icons could be cut by around half not to waste so much space.

**Comment by jhasse** [comment]
> I think the space between the icons could be cut by around half not to waste so much space. Leaves more space for more extensions and indicators then too.

Check out https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/ for that :)

**Comment by cra0zy** [comment]
@jhasse unrelated, but I don't know where else to ask you, will https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/33fcc8e88b1b0f493c30fdeceab4adb0dcba7479 ever get undo-d?

**Comment by orschiro** [comment]
@jhasse 

**With** XDG_CURRENT_DESKTOP=Unity:
![image](https://user-images.githubusercontent.com/170947/31849251-0fd0e3b6-b640-11e7-916f-695f318f32d0.png)

**Without** XDG_CURRENT_DESKTOP=Unity:
![image](https://user-images.githubusercontent.com/170947/31849259-1df00ada-b640-11e7-883e-3385ca97c60c.png)

**Comment by orschiro** [comment]
Something got fixed here. Thanks so much!

![image](https://user-images.githubusercontent.com/170947/31853062-11d82adc-b683-11e7-9172-c511a25453c6.png)

**Comment by jhasse** [comment]
@cra0zy Not right now, since we're missing the manpower to maintain this. Thanks for the commit, I didn't know that existed :)

@orschiro Hm ... I didn't push a new version. I guess you're using Ubuntu's version? Judging from your screenshot it looks like Telegram is now using TopIcons Plus instead.


I've pushed the +2 fix and will upload a new version to extensions.gnome.org now. Please open a new issue for any issues that arise.

**Comment by orschiro** [comment]
@jhasse sorry, my bad. I think it still looks like this because I used [1]. 

[1] orschiro@x230:~$ XDG_CURRENT_DESKTOP=Unity Telegram/Telegram

**Comment by orschiro** [comment]
@jhasse I see this issue is being closed but the problem with Telegram persists.

Related: https://github.com/telegramdesktop/tdesktop/issues/3968

![image](https://user-images.githubusercontent.com/170947/32433376-05624ed6-c2db-11e7-83fa-0fac8c88e873.png)

**Comment by jhasse** [comment]
Are you using the latest version of this extension?

**Comment by orschiro** [comment]
@jhasse I assume so because I have all latest updates for Ubuntu 17.10 installed.

![image](https://user-images.githubusercontent.com/170947/32444174-ef0dc49a-c301-11e7-8221-36183c522623.png)

**Comment by jhasse** [comment]
@orschiro Unfortunately no, the Ubuntu version lack's the last two commits.

See https://github.com/ubuntu/gnome-shell-extension-appindicator/tree/ubuntu

**Comment by orschiro** [comment]
@jhasse thanks for addressing the issue! I guess we just need to wait for the update then?

**Comment by didrocks** [comment]
@orschiro Do you mind opening a bug on launchpad with a detail (step by step) test case again the gnome-shell-extension-appindicator package? I'm happy to SRU it then so that you get the last commit.

**Comment by orschiro** [comment]
@didrocks done [1]. Thanks for addressing this!

[1] https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1730406

**Comment by jhasse** [comment]
I've increased the icon size once more, should be 22px now. This should make them as large as with TopIcons. Please test the latest master version and share your opinions :)

**Comment by orschiro** [comment]
Thanks!

Will follow the instructions [1] to check out the new 22px size. 

On a sidenote, if I change Top Icons Plus to 22px it somehow doesn't look right. See Hangouts.

[1] https://github.com/ubuntu/gnome-shell-extension-appindicator#installation

![image](https://user-images.githubusercontent.com/170947/33217602-dc67d61a-d138-11e7-800b-e590581f8cc4.png)

**Comment by robfrawley** [comment]
_The icons are way too large now..._ They outsize the core gnome icons by a factor of 33%, easily.

Sure, it would be nice for sizing to be configurable for those that want crazy sized icons, **but the default should not be that**. The vast majority of people want icons from this extension that _are the same size as the network/audio/battery icons sitting right next to them_, not larged than the system icons.

Making these icons larger than the system icons makes it visually obvious this is an extension: the default should appear visually identical to the sizing of the system icons so that it looks like this is a core-gnome-supported feature.

The best extensions fade away and blend into the gnome environment; the changes made as a result of this PR cause way oversized icons and make the icons originating from this extension appear to be out of place with the desktop environment design.

**Comment by jhasse** [comment]
> The vast majority of people want icons from this extension that are the same size as the network/audio/battery icons sitting right next to them, not larged than the system icons.

You don't know that.

**Comment by JasonLG1979** [comment]
I know I've said this before but even if it's a matter of manually resizing an icon you should be able to extract the icon size currently being used by the other panel icons from "system-status-icon" style class.

**Comment by cra0zy** [comment]
> You don't know that.

Thats... such a bad statement on your part @jhasse ...

**Comment by jhasse** [comment]
Why?

**Comment by JasonLG1979** [comment]
@cra0zy I would a agree with you that consistent icon size in the panel makes for a more seamless look and generally is just better design.

**Comment by linvain** [comment]
Had the same issue on Arch Linux (GNOME 3.30.2)

Adding `icon_size += 4` to `_init` method in `~/.local/share/gnome-shell/extensions/appindicatorsupport\@rgcjonas.gmail.com/appIndicator.js` solved this. The icons appear the same size as they are on Ubuntu 🎉

**Comment by Feichtmeier** [comment]
@jhasse the icons are still too big. The best would be if they would have the same size as the gnome status menu icons in the right corner

**Comment by hexauniverse** [comment]
Here's a solution for making icons normal sized:
Just replaсe `appIndicator.js` in extension folder with [this](https://a.doko.moe/sauegt.js) (I don't remember what I've changed)
