### ISSUE TITLE
Menu not working with Steam

### ISSUE THREAD

**Issue by jhasse** [ubuntu/gnome-shell-extension-appindicator#73]
On some systems clicking the Steam indicator doesn't open the menu.

**Comment by CopperBezel** [comment]
Similar to the now-fixed issue with Dropbox. Steam icon appears normally, but clicking it doesn't produce a menu or any visible effect. Gnome 3.22 on Ubuntu GNOME 17.04.

**Comment by jhasse** [comment]
The menu still works for me with Ubuntu 16.04, GNOME Shell 3.18.5 and Steam from Apr 20 2017.

What Steam (Help -> About) version do you have?

**Comment by CopperBezel** [comment]
Hmm. How odd.

I have the same version, Apr 20 2017, with "package versions" of 1492730551.

**Comment by steamlinux** [comment]
I have same problem
no menu, only icon
debian sid, steam beta, gnome 3.22

**Comment by giox069** [comment]
I'm the developer of  Remmina (another software which make use of libappindicators).
I noticed that when the menu is too high (because it contains too many elements), it will never appear. So, when you click on the icon, no menu appears. I can see that also Steam lists all your game in the menu, so, can be a long game list the problem? Can this extension make the menu automatically scrollable when it's too tall for the screen?

**Comment by steamlinux** [comment]
before steam menu normally work
now steam menu normally work with Top Icons Plus (another extension for this) and use half height

**Comment by steamlinux** [comment]
today extension updated and this bug not fixed

**Comment by jhasse** [comment]
That's why the issue is still open ;)

**Comment by jhasse** [comment]
> Can this extension make the menu automatically scrollable when it's too tall for the screen?

Not sure. See #69.

**Comment by AccountOneOff** [comment]
Installing `libdbusmenu-gtk4:i386` on Ubuntu 17.04 worked.

**Comment by jhasse** [comment]
@steamlinux Can you confirm that?

**Comment by steamlinux** [comment]
I use debian sid and after update "appandicator" libs I doesn't have this trouble
P.S. before my 1st post on this thread libdbusmenu-gtk4 and libdbusmenu-gtk4:i386 already installed
oh my poor english

**Comment by jhasse** [comment]
So ... this is fixed for you? Can I close this issue?

**Comment by steamlinux** [comment]
yes, this is fixed for me
thank's
