### ISSUE TITLE
Support for GoldenDict?

### ISSUE THREAD

**Issue by Sadi58** [ubuntu/gnome-shell-extension-appindicator#80]
This is a versatile dictionary utility using offline and customizable online dictionaries: http://goldendict.org/
And it is the only one left out in my desktop; any chance of including it as well please?

**Comment by jhasse** [comment]
I'm not sure I understand what you are asking for. Is there an app for Linux which you would want to use with this extension?

**Comment by Sadi58** [comment]
Yes, it is called **goldendict**.

**Comment by JasonLG1979** [comment]
It's up to the app to implement either appindicator support or org.kde.StatusNotifierWatcher support. If they do the app will show up. If you wish the app to show up in this extension you should file a bug with them.
