### ISSUE TITLE
Move to ubuntu organisation

### ISSUE THREAD

**Issue by jhasse** [ubuntu/gnome-shell-extension-appindicator#82]
Ubuntu is thinking about including this extension in 17.10 by default. They want a similar approach as dash-to-dock (forking it with an ubuntu branch): https://github.com/ubuntu/dash-to-dock

@rgcjonas Since you are no longer maintaining it, would you agree to move/transfer the repository completely to https://github.com/ubuntu ? They could also fork it, but in my experience this will result in lots of duplicated issues on GitHub.

**Comment by 3v1n0** [comment]
It has to be clear that anyone who had write permission in this repo, will get it too under the Ubuntu umbrella, keeping the `master` under the community control, while ubuntu will have its own branch for packaging and modifications that can't be merged to master.

**Comment by rgcjonas** [comment]
I'm totally in favor of transferring the repo to the ubuntu organization :+1: 

I just tried intiating the transfer but got the error "You don’t have the permission to create repositories on ubuntu". How do we proceed here?

**Comment by didrocks** [comment]
Do you mind adding myself to this repo, and I'll do the transfer thus?

**Comment by rgcjonas** [comment]
@didrocks I added you as collaborator

**Comment by didrocks** [comment]
I don't have access to the repository settings apparently. I guess I need "admin" priviledges to initiate the transfer.

**Comment by rgcjonas** [comment]
What a bummer! I have contacted the Github support for advice:

> Subject: Need Advice: Transfer personal Repo to Organization w/o write access
>
> https://github.com/rgcjonas/gnome-shell-extension-appindicator/issues/82
>
>We're trying to move the repo over to the ubuntu organization. I can't do it because I don't have write access to the ubuntu organization (and that's not supposed to change), @didrocks can't do it because he doesn't have admin access to my repo (and while I wouldn't mind, I can't give it to him).
>
>I figured I could maybe transfer the repo to @didrocks and then he can transfer it to the ubuntu org but it seems like a hack. Is there a proper way to directly transfer the repo?

**Comment by rgcjonas** [comment]
I have a reply from GitHub:
>
>>  I figured I could maybe transfer the repo to @didrocks and then he can transfer it to the ubuntu org but it seems like a hack. Is there a proper way to directly transfer the repo?
>
>This is the proper way. Let me know if you have any other questions!

**Comment by rgcjonas** [comment]
Error: "didrocks/gnome-shell-extension-appindicator already exists" 

@didrocks you need to delete your fork then I can initiate the transfer

**Comment by didrocks** [comment]
Thanks for looking at this! This is now done. Mind transferring?

**Comment by rgcjonas** [comment]
Transfer has been started

**Comment by didrocks** [comment]
Thanks a lot! Transfer is now done and I retransfered to the ubuntu organization. It seems that both of you are still set as collaborators, so I guess you have the correct permissions to the repo. Shout if it's not the case :)

Thanks to both of you for your swift replies and helping us greatly on this!

**Comment by jhasse** [comment]
@didrocks You should have admin rights now, correct? Can you set a description and the homepage to https://extensions.gnome.org/extension/615/appindicator-support/ for the GitHub project?

**Comment by didrocks** [comment]
Yes! And it's done now :)
