### ISSUE TITLE
Pidgin shows on the button of the screen(ubuntu 17.10)

### ISSUE THREAD

**Issue by garnus** [ubuntu/gnome-shell-extension-appindicator#83]
As above, pidgin don't work with this exentsion. 
I installed pidgin-indicator and enabled the extension.
After this i have 2 pidgin icons, one on the top and one of the buttom of the screen.

**Comment by jhasse** [comment]
Does the one in the bottom left go away if you disable it in Pidgin's settings?

**Comment by garnus** [comment]
How do i can disable the main pidgin icon?

**Comment by jhasse** [comment]
Tools -> Preferences -> Interface -> Show sytem tray icon: Never

**Comment by garnus** [comment]
It's working. Thank you you made my day.

**Comment by jhasse** [comment]
You're welcome :)
