### ISSUE TITLE
Replace "Fix me" with correct names for menus

### ISSUE THREAD

**Issue by jhasse** [ubuntu/gnome-shell-extension-appindicator#85]
Comment from extensions.gnome.org:

Please add applet / indicator names to menus created by this extension. Currently every menu has a name of "fix me" or something like that. That is confusing when you are using screen reader. I am blind so I have to use computer using the Orca screen reader. Currently if I select any of the menus created by this extension then Orca screen reader says "Fix me menu". That is confusing because it is impossible to know what menu is what.

**Comment by 3v1n0** [comment]
I've tested this again, and I think this is now fixed.

The `FIXME` term is in fact used as a placeholder while a menu item has no label (and the same would see someone reading), once the label is set, the accessibility value should match.

And in fact it does from my tests.
