### ISSUE TITLE
Telegram Desktop not working

### ISSUE THREAD

**Issue by jhasse** [ubuntu/gnome-shell-extension-appindicator#88]
https://desktop.telegram.org/

See #87. Needs to be further investigated, code looks like this: https://github.com/telegramdesktop/tdesktop/blob/8884cb190aec02bf3cfc5a8fae74de18aebdb230/Telegram/SourceFiles/platform/linux/linux_libs.cpp#L245

**Comment by makruiten** [comment]
Same for Fedora 26 on Gnome 3.24. Remmina does show up, but not Telegram. Fedora has libappindicator3.so by default (or at least I have it), but I even installed libappindicator from the repositories, which installs additional packages (don't know what's different about them). Doesn't help. Don't know if it's relevant, but it does work in both Topicons and Topicons Plus.

**Comment by jhasse** [comment]
Found it! https://github.com/telegramdesktop/tdesktop/blob/c1aa1c5a0f26b29fce1307ba455f9887e7c1c1ec/Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp#L123

This should be replaced with a check for the DBus interfaces as mentioned here: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74#issuecomment-326624417

I've created an upstream issue: https://github.com/telegramdesktop/tdesktop/issues/3927

**Comment by makruiten** [comment]
I [referenced](https://github.com/openambitproject/openambit/issues/168) the upstream issue at OpenAmbit, which I'm using. If anyone with more knowledge than me has anything to add or correct, please do so.

**Comment by jhasse** [comment]
Fixed by https://github.com/telegramdesktop/tdesktop/pull/3930
