### ISSUE TITLE
Unsupported features that are intresting to implement?

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-extension-appindicator#92]
In Unity, oversized icons and labels for indicators are supported for example, but just maybe because they are in intoning with the Unity design principles, but maybe not with the ubuntu vision of the gnome shell.

Them, what are the missing features that are interesting to be implemented?

The readme file don't specify really. There are also another feature like a black list for indicators, that are also not mention.

**Comment by lestcape** [comment]
Please see some change that was introduced here, maybe some of then are interesting others not:
https://github.com/linuxmint/Cinnamon/pull/5790

**Comment by jhasse** [comment]
Oversized icons is the most interesting one for me, since I would love to use the multiload indicator :)

**Comment by 3v1n0** [comment]
This is now fixed.
