### ISSUE TITLE
Support for FireTray and Google Hangouts?

### ISSUE THREAD

**Issue by orschiro** [ubuntu/gnome-shell-extension-appindicator#99]
Hi all, 

I have those two programs for which I currently need [Top Icons](https://extensions.gnome.org/extension/495/topicons/) to show their icons:

![image](https://user-images.githubusercontent.com/170947/31704968-e21cf53a-b3e3-11e7-89b1-dc865fa5c77e.png)

These icons come from [FireTray](https://github.com/foudfou/FireTray) for Thunderbird and [Google Hangouts](https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd) from Chrome.

My question, is it within the scope of gnome-shell-extension-appindicator to support those two or should users continue to rely on TopIcons?

Thank you!

**Comment by jhasse** [comment]
Hi, thanks for opening the issue :)

For Chrome you'll have to wait for https://bugs.chromium.org/p/chromium/issues/detail?id=419673 to be fixed.

As for FireTry: I don't know, it seems to be deprecated. I found https://github.com/tanwald/gnome-shell-extension-thunderbird-integration, but that also seems to be deprecated. Maybe someone else who uses Thunderbird knows the current situation there?

**Comment by orschiro** [comment]
@jhasse, thanks, really appreciate your comment!

Hence, Hangouts resolved. 

I guess for FireTray I will keep on relying on TopIcons since tb-gnome-shell-integration doesn't provide a tray icon which I want and need to run TB in the background without having to have the main window opened.

**Comment by jhasse** [comment]
I hope it's okay if I close this for now, not much we can do about Thunderbird. There's the infamous bug report about tray icon support https://bugzilla.mozilla.org/show_bug.cgi?id=208923 but I doubt that it will get fixed soon.

**Comment by orschiro** [comment]
Totally understandable. Thanks though, Jan!
